import { useState } from 'react'
import type { ProposedAction } from '../../contracts/types'
import { ReviewDialog } from '../../components/ReviewDialog'
import { DataValue } from '../investigation/Science'
export function IterationModal({action,parentRunId,currentParameters={},onApprove,onReject}: {action:ProposedAction;parentRunId:string;currentParameters?:Record<string,unknown>;onApprove:(a:ProposedAction)=>void;onReject:()=>void}) {
  const [parameters,setParameters] = useState<Record<string,string|number|boolean>>(action.parameters ?? {})
  const [reason,setReason] = useState(action.description)
  const [key,setKey] = useState(''), [value,setValue] = useState('')
  const add = () => {if(key.trim()){const old = currentParameters[key];setParameters({...parameters,[key]:typeof old==='number' && value.trim() && Number.isFinite(Number(value)) ? Number(value) : typeof old==='boolean' && ['true','false'].includes(value) ? value==='true' : value});setKey('');setValue('')}}
  return <ReviewDialog title="Create a child run" onClose={onReject}><p className="quiet">Review the proposed change before execution.</p><DataValue value={{parent_run:parentRunId,source_evidence:action.sourceEvidenceId,source_stage:action.sourceNodeId}}/><div className="science-table-scroll"><table className="science-table"><thead><tr><th>Parameter</th><th>Current value</th><th>New value</th><th></th></tr></thead><tbody>{Object.entries(parameters).map(([k,v]) => <tr key={k}><th>{k}</th><td><DataValue value={currentParameters[k]}/></td><td><input aria-label={`New value for ${k}`} value={String(v)} onChange={e => setParameters({...parameters,[k]:typeof v==='number' && Number.isFinite(Number(e.target.value)) ? Number(e.target.value) : typeof v==='boolean' ? e.target.value==='true' : e.target.value})}/></td><td><button className="text-action" onClick={() => setParameters(Object.fromEntries(Object.entries(parameters).filter(([name]) => name!==k)))}>Remove</button></td></tr>)}</tbody></table></div><div className="parameter-add"><input aria-label="Parameter name" placeholder="Parameter" list="parameter-names" value={key} onChange={e => setKey(e.target.value)}/><datalist id="parameter-names">{Object.keys(currentParameters).map(k => <option key={k}>{k}</option>)}</datalist><input aria-label="Parameter value" placeholder="New value" value={value} onChange={e => setValue(e.target.value)}/><button className="text-action" disabled={!key.trim()} onClick={add}>Add change</button></div><label className="stacked-label">Reason<textarea value={reason} onChange={e => setReason(e.target.value)}/></label><div className="dialog-actions"><button className="text-action" onClick={onReject}>Cancel</button><button className="primary" disabled={!reason.trim()} onClick={() => onApprove({...action,parameters,description:reason})}>Create Child Run</button></div></ReviewDialog>
}
