import { useEffect, useState } from 'react'
import { ArrowLeft, Database, FileCheck2 } from 'lucide-react'
import { CopyValue, DataValue, Empty, ScientificTable, Section } from '../investigation/Science'
import { label as baseLabel } from '../investigation/presentation'
const label=(value:string)=>({xgboost:'XGBoost',lightgbm:'LightGBM',lightgbm_balanced:'LightGBM Balanced',xgboost_weighted:'XGBoost Weighted',mlp:'MLP',mlp_tabular:'MLP · tabular',lstm:'LSTM',lstm_sequence:'LSTM · sequence',gru:'GRU',gru_sequence:'GRU · sequence',simple_cnn_vision:'CNN · vision',simple_cnn_small:'CNN · small',ncf:'NCF',ffm:'FFM',fm:'FM',mf:'MF',hrp:'HRP',erc:'ERC',min_variance:'Minimum Variance',xai_certification:'XAI certification',gpt41_policy_certification:'GPT-4.1 policy certification',shap_tree_explainer:'SHAP · Tree Explainer',partial_dependence_plot:'PDP · Partial Dependence',individual_conditional_expectation:'ICE · Individual Conditional Expectation',accumulated_local_effects:'ALE · Accumulated Local Effects',lime_tabular_explainer:'LIME · Tabular Explainer'} as Record<string,string>)[value]??baseLabel(value)
import { comparisonRows, datasetIdentities, domains, experimentRuns, experimentTrace, layerLabel, providers, type CertificationBundle, type ComparisonRow, type RecordData } from './bundle'
import './certification.css'
import { LiveDataRuntime } from './LiveDataRuntime'
import { loadLiveCertification } from './liveApi'
import { LiveSeedDetail, LiveRunPresentation } from './LiveRunPresentation'

export function CertificationSurface({surface, context, onReturn}:{surface:'data'|'certification';context?:string;onReturn:()=>void}) {
  const [dataVisited,setDataVisited]=useState(surface==='data')
  useEffect(()=>{if(surface==='data')setDataVisited(true)},[surface])
  const [bundle,setBundle]=useState<CertificationBundle|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0)
  useEffect(()=>{const controller=new AbortController();setError('');setBundle(null);loadLiveCertification(controller.signal).then(setBundle).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>controller.abort()},[attempt])
  return <main className="cert-workspace"><button className="text-action cert-back" onClick={onReturn}><ArrowLeft size={15}/> Return to workspace</button>
    <header className="cert-heading"><span className="eyebrow">StART / {surface==='data'?'DATA PLANE':'SCIENTIFIC ASSURANCE'}</span><h1>{surface==='data'?<Database size={27}/>:<FileCheck2 size={27}/>} {surface==='data'?'Data Runtime':'Scientific Certification'}</h1><p>{surface==='data'?'Inspect live provider readiness, resolve dataset contracts, and follow bounded ingestion.':'Inspect the results, assumptions, and limits of deterministic scientific verification.'}</p></header>
    <div hidden={surface!=='data'}>{dataVisited&&<LiveDataRuntime context={context}/>}</div>
    <div hidden={surface!=='certification'}>{error?<Empty title="Live certification unavailable"><span role="alert">{error}</span><button className="tonal" onClick={()=>setAttempt(x=>x+1)}>Retry live API</button></Empty>:!bundle?<p role="status">Loading live certification evidence…</p>:<><div className="cert-source"><span>Live API · generated {bundle.certification_manifest.timestamp}</span><code>{bundle.certification_manifest.certification_id}</code><span>Fetched {bundle.packaged_at}</span><button className="text-action" onClick={()=>setAttempt(x=>x+1)}>Refresh certification</button></div><ScientificCertification bundle={bundle}/></>}</div>
  </main>
}
function Status({value}:{value:unknown}) {return <span className="cert-status" data-limited={/PARTIAL|BLOCKED|DEFERRED|NOT_EXECUTABLE|NOT_EVALUATED|UNAVAILABLE|EXCLUD|LOCAL/i.test(String(value))||undefined}>{String(value??'Unavailable')}</span>}
function Detail({title,value}:{title:string;value:unknown}) {return <details className="cert-detail"><summary>{title}</summary><DataValue value={value}/></details>}
export function DatasetIdentity({dataset}:{dataset:RecordData}) {return <article className="cert-identity"><div className="eyebrow">{layerLabel(dataset.layer)}</div><h3>{dataset.dataset_id}</h3><dl className="cert-facts">{[['Provider',providers[dataset.provider]??dataset.provider],['Revision',dataset.revision],['Recorded rows',dataset.rows],['Features',dataset.features],['Target',dataset.target]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v??'Unavailable'}</dd></div>)}</dl><div className="cert-fingerprint"><span>Dataset fingerprint · SHA-256</span>{dataset.fingerprint?<CopyValue value={dataset.fingerprint} truncate/>:<span>Unavailable</span>}</div>{dataset.license&&<p className="quiet">{dataset.license} · {dataset.citation}</p>}</article>}
function ScientificCertification({bundle}:{bundle:CertificationBundle}) {
  const [domain,setDomain]=useState(bundle.champion_challenger[0]?.domain??''),[experiment,setExperiment]=useState(bundle.champion_challenger.find(r=>r.layer==='real_external')?.experiment_id??'')
  const candidates=bundle.champion_challenger.filter(c=>c.domain===domain)
  const result=candidates.find(c=>c.experiment_id===experiment)??candidates[0]
  const runs=result?experimentRuns(bundle,result.experiment_id):[]
  const coverage=bundle.real_data_domain_coverage.find(c=>c.domain===domain)
  const identities=datasetIdentities(bundle,runs)
  return <>
    <div className="cert-assurance"><div><span className="eyebrow">OVERALL SCOPE · PRODUCT CERTIFICATION BRIEF</span><h2>Certified with exclusions</h2><code>CERTIFIED_WITH_EXCLUSIONS</code><p>Dimension values below are supplied by the current bundle. Certification applies to the recorded scope.</p></div><dl className="cert-dimensions">{Object.entries(bundle.certification_manifest.status_dimensions).map(([key,v])=><div key={key}><dt>{label(key)}</dt><dd><Status value={v}/></dd></div>)}</dl></div>
    <Exclusions bundle={bundle}/>
    <div className="cert-selector"><label className="cert-select">Scientific domain<select aria-label="Scientific domain" value={domain} onChange={e=>{setDomain(e.target.value);setExperiment('')}}>{[...new Set(bundle.champion_challenger.map(r=>r.domain))].map(id=><option key={id} value={id}>{domains[id]??label(id)}</option>)}</select></label>{candidates.length>1&&<label className="cert-select">Evaluation scope<select aria-label="Evaluation scope" value={result.experiment_id} onChange={e=>setExperiment(e.target.value)}>{candidates.map(c=><option key={c.experiment_id} value={c.experiment_id}>{layerLabel(c.layer)} · {c.dataset}</option>)}</select></label>}</div>
    <div className="cert-domain" key={result?.experiment_id??domain}><header><span className="eyebrow">CERTIFICATION DOMAIN</span><h2>{domains[domain]}</h2><p className="quiet">Domain coverage record · applies across evaluation scopes</p><Status value={coverage?.status}/><p className="quiet">Real external dataset executed: {coverage?.real_dataset_executed===true?'Yes':coverage?.real_dataset_executed===false?'No':'Unavailable'}</p><p className="quiet">{coverage?.blocker_reason??coverage?.note??coverage?.notes}</p><p className="quiet">Seeds: {bundle.certification_manifest.seeds?.join(', ')} · {result?.experiment_id}</p></header>
    {identities.map(d=><DatasetIdentity key={`${d.dataset_id}:${d.fingerprint}`} dataset={d}/>)}
    {!result?<Empty title="No domain result supplied"/>:<>
      {result.presentation_limitation&&<p className="cert-notice">{result.presentation_limitation}</p>}{domain==='portfolio'?<><Portfolio result={result}/>{runs[0]&&<LiveRunPresentation runId={runs[0].run_id} kind="portfolio"/>}</>:domain==='market_risk'?<Section title="Calibration and quantile diagnostics" note={result.governance_note}><ScientificTable rows={Object.entries(result.calibration_diagnostics??{}).map(([method,v])=>({method,...v as RecordData}))}/><p className="quiet">DO_NOT_REJECT is the reported coverage-test decision, not proof of model superiority. Seed-level p-values remain inspectable below.</p></Section>:domain==='scenario_traded_risk'?<Section title="Known-answer invariant ledger" note={result.governance_note}><DataValue value={{method:result.champion_model,metric:result.primary_metric,reported_mean:result.champion_mean,reported_std:result.champion_std,reported_ci95:result.champion_ci95}}/><p className="quiet">This method is shown as a repricing verification, not a ranked champion. Unit/provenance and Gate-6A integrity checks are not separately emitted.</p></Section>:<Comparison result={result}/>}
      {(domain==='scenario_traded_risk'||domain==='portfolio'||domain==='market_risk'||domain==='recommender')&&<Invariants bundle={bundle} domain={domain}/>}
      {domain==='scenario_traded_risk'&&runs[0]&&<LiveRunPresentation runId={runs[0].run_id} kind="scenario"/>}<Seeds runs={runs}/><Policy bundle={bundle} result={result}/>
      {domain==='predictive_binary'&&result.layer==='real_external'&&<Explainability bundle={bundle} dataset={result.dataset}/>}
      {domain==='fraud_imbalanced'&&<p className="cert-notice">This matrix covers the emitted supervised golden-data challengers. Unsupervised anomaly detection and Graph AML are not certified by this bundle.</p>}
    </>}</div>
    <Section title="Mathematical invariants" note="Exact checks recorded independently of empirical model performance."><Detail title="Inspect the complete invariant ledger" value={bundle.invariant_results}/></Section><Provenance bundle={bundle}/>
  </>
}
function Exclusions({bundle}:{bundle:CertificationBundle}) {return <section className="cert-exclusions" aria-label="Certification exclusions"><h2>Exclusions & limits</h2><div className="cert-exclusion-grid">{bundle.real_data_domain_coverage.filter(r=>r.real_dataset_executed===false).map(r=><div key={r.domain}><strong>{domains[r.domain]??label(r.domain)} · real data not executed</strong><Status value={r.status}/><p>{r.blocker_reason??r.note??r.notes}</p></div>)}{bundle.xai_results.filter(r=>r.status==='NOT_EXECUTABLE').map(r=><div key={r.method}><strong>{label(r.method)}</strong><Status value={r.status}/><p>{r.reason}</p></div>)}{Object.values(bundle.runtime.providers??{}).filter((r:any)=>!r.runnable).map((r:any)=><div key={r.name}><strong>{providers[r.name]??r.name}</strong><Status value={r.status}/><p>{r.details}</p></div>)}<div><strong>Distributed runtime</strong><Status value={bundle.certification_manifest.status_dimensions.distributed_data_runtime_certification}/><p>Ray distributed execution verified: {String(bundle.certification_manifest.environment.ray_distributed_execution_verified)}.</p></div>{bundle.failures.map((f,i)=><div key={i}><strong>{f.model??'Recorded exclusion'}</strong><p>{f.note??f.exception}</p><span className="quiet">Fail-closed contract: {f.fail_closed_contract??'Unavailable'}</span></div>)}</div></section>}
function Comparison({result}:{result:RecordData}) {
  const rows=comparisonRows(result)
  return <Section title={result.architectures_certified?'Architecture-specific results':'Champion / challenger'} note="Reported aggregates in backend order. No rankings or statistics are calculated in the browser."><div className="science-table-scroll"><table className="science-table cert-comparison"><thead><tr>{['Model','Designation / task','Primary metric','Mean','Std','95% CI','Policy'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.model}><th>{label(r.model)}</th><td>{r.task??r.designation}</td><td>{r.metric}</td><td><NumberValue value={r.mean}/></td><td><NumberValue value={r.std}/></td><td>{r.ci95?.map(String).join(' – ')??'Unavailable'}</td><td>{r.policy??'Unavailable'}</td></tr>)}</tbody></table></div>{[...new Set(rows.map(r=>r.metric))].map(metric=><ConfidencePlot key={metric} rows={rows.filter(r=>r.metric===metric)} metric={metric}/>)}<p className="quiet">Secondary metrics and exact configuration are available in seed-level evidence. {result.architectures_certified&&'Different tasks are not a single model competition; confidence bounds are displayed as supplied, including bounds above 1.'}</p></Section>
}
function NumberValue({value}:{value?:number}) {return typeof value==='number'?<span title={String(value)}>{value.toLocaleString('en-US',{maximumSignificantDigits:7})}</span>:<span className="quiet">Unavailable</span>}
function ConfidencePlot({rows,metric}:{rows:ComparisonRow[];metric:string}) {
  const valid=rows.filter(r=>typeof r.mean==='number'&&r.ci95?.length===2&&r.ci95.every(Number.isFinite))
  if(!valid.length)return null
  const lo=Math.min(...valid.flatMap(r=>[r.mean,...r.ci95!])), hi=Math.max(...valid.flatMap(r=>[r.mean,...r.ci95!]))
  const x=(v:number)=>hi===lo?445:230+(v-lo)/(hi-lo)*430
  return <figure className="cert-ci"><svg viewBox={`0 0 740 ${valid.length*40+52}`} role="img" aria-label={`Supplied 95% confidence intervals for ${metric}`}>{valid.map((r,i)=><g key={r.model}><text x="8" y={i*40+26}>{label(r.model)}</text><line x1={x(r.ci95![0])} x2={x(r.ci95![1])} y1={i*40+22} y2={i*40+22}/>{r.ci95!.map((v,j)=><line key={j} x1={x(v)} x2={x(v)} y1={i*40+16} y2={i*40+28}/>)}<circle cx={x(r.mean)} cy={i*40+22} r="4"><title>{r.model}: {r.mean}; 95% CI {r.ci95!.join(', ')}</title></circle></g>)}<text x="230" y={valid.length*40+28}>{lo.toPrecision(5)}</text><text x="660" textAnchor="end" y={valid.length*40+28}>{hi.toPrecision(5)}</text></svg><figcaption>{metric} · points: supplied means · bars: supplied 95% CI</figcaption></figure>
}
function Seeds({runs}:{runs:RecordData[]}) {
  const models=[...new Set(runs.map(r=>r.model))], [selected,setSelected]=useState(''),[policy,setPolicy]=useState('all')
  const model=models.includes(selected)?selected:models[0]
  const filtered=runs.filter(r=>r.model===model&&(policy==='all'||r.policy===policy))
  return <Section title="Seed-level evidence" note="Exact JSONL observations, not recalculated aggregates."><div className="cert-selector"><label className="cert-select">Model<select aria-label="Seed evidence model" value={model} onChange={e=>setSelected(e.target.value)}>{models.map(m=><option key={m} value={m}>{label(m)}</option>)}</select></label><label className="cert-select">Policy<select aria-label="Seed evidence policy" value={policy} onChange={e=>setPolicy(e.target.value)}><option value="all">All recorded policies</option><option value="deterministic">Deterministic</option><option value="gpt41">GPT-4.1 plan</option></select></label></div>{filtered.length?filtered.map(r=><LiveSeedDetail key={r.run_id} run={r}/>):<Empty title="No seed records for this selection"/>}</Section>
}
function Policy({bundle,result}:{bundle:CertificationBundle;result:RecordData}) {
  const trace=experimentTrace(bundle,result.experiment_id)
  const runs=experimentRuns(bundle,result.experiment_id), coverage=bundle.gpt41_policy_coverage.find(c=>c.domain===result.domain)
  const policies=runs.filter(r=>r.policy==='gpt41')
  const baselines=runs.filter(r=>r.policy==='deterministic'&&r.seed===0)
  const config=(r:RecordData)=>({model:r.model,preprocessing:r.preprocessing,hyperparameters:r.hyperparameters,split:r.split,primary_metric:r.primary_metric_name,tuning_strategy:r.tuning_strategy,trial_budget:r.trial_budget})
  return <Section title="Deterministic policy vs GPT-4.1 policy" note="GPT-4.1 proposes configuration only. All reported numerical results are produced by StART deterministic scientific engines.">{trace&&policies.length?<><DataValue value={result.gpt41_vs_deterministic}/><div className="cert-policy-grid"><div><h3>Deterministic policy</h3>{baselines.map(r=><Detail key={r.model} title={`${label(r.model)} · recorded seed 0 configuration`} value={config(r)}/>)}</div><div><h3>GPT-4.1 policy</h3><DataValue value={{model:trace.model,planning_call_id:trace.call_id,prompt_tokens:trace.prompt_tokens,completion_tokens:trace.completion_tokens,latency_seconds:trace.latency_seconds,numeric_authority:bundle.certification_manifest.policies?.gpt41_numeric_authority,schema_valid:trace.schema_valid}}/><Detail title="Proposed configuration · planning response" value={trace.response_parsed}/><Detail title="Recorded execution configuration · seed 0" value={config(policies[0])}/><Detail title="Policy coverage record" value={coverage}/></div></div><p className="quiet">Planning intent and recorded execution configuration are displayed separately. A proposed tuning budget does not establish completed tuning trials.</p></>:<Empty title="No GPT-4.1 comparison for this evaluation">{coverage?.status?.startsWith('EXCLUDED')?coverage.status:'No matching planning call or GPT-4.1 seed records were emitted for this experiment. Golden-data policy results are available under their own scope.'}</Empty>}<Detail title="Experiment specification · supplied records only" value={bundle.experiment_matrix.filter(r=>r.experiment_id===result.experiment_id)}/><Empty title="Tuning trial observations unavailable">Run records contain strategy and trial budget. The bundle does not emit completed trial observations, best-trial parameters, or promotion evidence.</Empty></Section>
}
function Explainability({bundle,dataset}:{bundle:CertificationBundle;dataset:string}) {return <><Section title="Explainability methods" note="Independent method audit records on the real predictive dataset. Numerical attributions and PDP / ICE curves were not emitted."><div className="cert-methods">{bundle.xai_results.filter(r=>r.dataset===dataset).map(r=><article key={r.method}><h3>{label(r.method)}</h3><Status value={r.status}/><DataValue value={Object.fromEntries(Object.entries(r).filter(([k])=>!['method','status','dataset'].includes(k)))}/></article>)}</div></Section><Section title="Sensitivity" note="Backend audit of One-at-a-Time and Parallel Basket on real predictive data.">{bundle.sensitivity_results.map(r=><article className="cert-sensitivity" key={r.mode}><h3>{r.mode==='one_at_a_time'?'One-at-a-Time':r.mode==='parallel_basket'?'Parallel Basket':label(r.mode)}</h3><Status value={r.status}/><ol className="cert-grid" aria-label={`${r.mode} shock grid`}>{r.shock_grid.map((v:number)=><li key={v} data-baseline={v===0||undefined}>{v>0?'+':''}{Math.round(v*100)}%{v===0&&<small>Baseline</small>}</li>)}</ol><DataValue value={{model:r.model,top_features:r.top_features,baseline_zero_delta:r.baseline_zero_delta,finite_metrics:r.finite_metrics}}/></article>)}<Empty title="Sensitivity response observations unavailable">The nine-point grid and zero-drift audit are supplied; response metrics at each shock are not. No response curve is inferred.</Empty></Section></>}
function Portfolio({result}:{result:RecordData}) {const data=result.multi_objective_evaluation??{}, methods=Object.keys(data);return <Section title="Portfolio · multi-objective allocation" note="Each objective has its own supplied result. There is no universal champion."><div className="science-table-scroll"><table className="science-table"><thead><tr><th>Metric</th>{methods.map(m=><th key={m}>{label(m)}</th>)}</tr></thead><tbody>{[['Volatility','mean_vol'],['Return','mean_ret'],['Sharpe','mean_sharpe'],['Diversification','mean_div_ratio'],['Diversification std','std_div_ratio'],['Concentration (HHI)','mean_hhi'],['Risk contribution','risk_contribution']].map(([name,key])=><tr key={key}><th>{name}</th>{methods.map(m=><td key={m}><NumberValue value={data[m][key]}/></td>)}</tr>)}</tbody></table></div><h3>Reported objective winners</h3><DataValue value={result.objective_winners}/><p className="quiet">A separate risk-dispersion / concentration winner and asset-level risk contributions were not emitted. Equal risk contribution is preserved as the backend's own objective label.</p></Section>}
function Invariants({bundle,domain}:{bundle:CertificationBundle;domain:string}) {return <Section title="Domain invariants">{bundle.invariant_results.filter(r=>r.domain===domain).map(r=><article className="cert-invariant" key={r.invariant_id}><div><h3>{r.description}</h3><Status value={r.status}/></div><DataValue value={{expected:r.expected,observed:r.observed,margin:r.margin,details:r.details}}/></article>)}</Section>}
function Provenance({bundle}:{bundle:CertificationBundle}) {return <Section title="Evidence & provenance" note="Live read API for the backend-loaded certification bundle. Certification seed IDs remain separate from workbench replay IDs."><DataValue value={{certification_id:bundle.certification_manifest.certification_id,generated_at:bundle.certification_manifest.timestamp,fetched_at:bundle.packaged_at,loaded_at:bundle.certification_manifest.loaded_at,bundle_hash:bundle.certification_manifest.bundle_hash}}/><Detail title="Source artifact fingerprints · supplied by backend" value={bundle.sources}/><Detail title="Certification manifest and environment" value={bundle.certification_manifest}/><Detail title="Historical discrepancy audit · not current certification status" value={bundle.certification_discrepancies}/><p className="quiet">Refresh reads the live bundle. The backend invalidates its cache when source artifacts change; generated and loaded times are reported separately.</p></Section>}
