import { useEffect, useRef, useState } from 'react'
import { DataValue, Empty, Section } from '../investigation/Science'
import { label } from '../investigation/presentation'
import { liveRequest } from './liveApi'
import type { RecordData } from './bundle'
export const terminalSession=(state:unknown)=>['COMPLETED','STOPPED','ERROR'].includes(String(state))
export function LiveDataRuntime({context}:{context?:string}) {
  const [registry,setRegistry]=useState<RecordData[]>([]),[runtime,setRuntime]=useState<RecordData|null>(null),[selected,setSelected]=useState('huggingface')
  const [discovery,setDiscovery]=useState<RecordData|null>(null)
  const [probe,setProbe]=useState<RecordData|null>(null),[query,setQuery]=useState('adult-census-income'),[datasets,setDatasets]=useState<RecordData[]>([])
  const [datasetId,setDatasetId]=useState(''),[revision,setRevision]=useState(''),[target,setTarget]=useState(''),[contract,setContract]=useState<RecordData|null>(null),[report,setReport]=useState<RecordData|null>(null)
  const [session,setSession]=useState<RecordData|null>(null),[telemetry,setTelemetry]=useState<RecordData|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[pollError,setPollError]=useState('')
  const [maxRows,setMaxRows]=useState(500),[batchSize,setBatchSize]=useState(100),[sampleRows,setSampleRows]=useState(100),[refreshed,setRefreshed]=useState('')
  const mounted=useRef(true), actionLock=useRef(false)
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[])
  const act=async(name:string,fn:()=>Promise<void>)=>{if(actionLock.current)return;actionLock.current=true;setBusy(name);setError('');try{await fn()}catch(e){if(mounted.current)setError((e as Error).name==='AbortError'?'Request timed out or was cancelled. Check the backend before retrying an ingestion request.':(e as Error).message)}finally{actionLock.current=false;if(mounted.current)setBusy('')}}
  const refresh=async()=>{const results=await Promise.allSettled([liveRequest('/data/providers'),liveRequest('/data/runtime')]);for(const r of results)if(r.status==='rejected')throw r.reason;const [p,r]=results.map(x=>(x as PromiseFulfilledResult<RecordData>).value);if(mounted.current){setRegistry(p.providers??[]);setRuntime(r);setRefreshed(new Date().toLocaleTimeString())}}
  useEffect(()=>{void act('Loading providers',refresh)},[])
  const provider=registry.find(p=>p.provider_id===selected)
  const active=!!session&&!terminalSession(telemetry?.state??session.state)
  useEffect(()=>{
    if(!session?.session_id)return
    const controller=new AbortController();let timer:ReturnType<typeof setTimeout>|undefined
    const poll=async()=>{try{const data=await liveRequest(`/data/sessions/${encodeURIComponent(session.session_id)}/telemetry`,{signal:controller.signal});if(controller.signal.aborted)return;setTelemetry(data);setPollError('');if(!terminalSession(data.state))timer=setTimeout(poll,1000)}catch(e){if(!controller.signal.aborted){setPollError('Telemetry connection lost; last measurement is stale. Stop remains available.');timer=setTimeout(poll,4000)}}}
    void poll();return()=>{controller.abort();if(timer)clearTimeout(timer)}
  },[session?.session_id])
  const resetIdentity=()=>{setContract(null);setReport(null)}
  const request=()=>({provider:selected,dataset_id:datasetId,revision:revision||null,target:target||null})
  const validBounds=Number.isInteger(maxRows)&&maxRows>=10&&maxRows<=2000&&Number.isInteger(batchSize)&&batchSize>=10&&batchSize<=maxRows
  return <>
    <div className="cert-source"><span>Live backend API · refreshed {refreshed||'not yet'}</span><button className="text-action" disabled={!!busy} onClick={()=>void act('Refreshing',refresh)}>Refresh provider state</button></div>
    {error&&<p className="cert-notice" role="alert">{error}</p>}{busy&&<p role="status">{busy}…</p>}
    <Section title="Provider registry" note="Dependency availability, credentials, connectivity, and streaming are independent backend states."><div className="cert-providers" role="group" aria-label="Data providers">{registry.map(p=><button key={p.provider_id} disabled={!!busy||active} aria-pressed={selected===p.provider_id} onClick={()=>{setSelected(p.provider_id);setProbe(null);setDatasets([]);setDiscovery(null);setDatasetId('');setRevision('');setTarget('');resetIdentity()}}><strong>{p.display_name}</strong><span className="cert-status">{p.status}</span></button>)}</div>{provider&&<div className="cert-provider-detail"><h3>{provider.display_name}</h3><p>{provider.reason_if_unavailable}</p><h4>Registry status</h4><LiveFacts data={provider} fields={['package_available','credential_required','credential_configured','runnable','remote_connectivity_verified','streaming_supported']}/><button className="tonal" disabled={!!busy||!provider.connection_test_supported} onClick={()=>void act('Probing connectivity',async()=>setProbe(await liveRequest(`/data/providers/${encodeURIComponent(selected)}/probe`)))}>Probe connectivity</button>{probe&&<><h4>Latest connectivity probe</h4><DataValue value={probe}/></>}<p className="quiet">Local / trusted backend session. The backend supports opaque provider sessions. Credential entry is unavailable here because multi-tenant isolation is not verified. Public dataset access remains available.</p></div>}</Section>
    <Section title="Dataset discovery" note="Search, resolve, and inspect data. These actions do not start model training."><details className="cert-detail" open><summary>Search or select a dataset</summary><form className="cert-selector" onSubmit={e=>{e.preventDefault();void act('Discovering datasets',async()=>{const data=await liveRequest(`/data/providers/${encodeURIComponent(selected)}/datasets?query=${encodeURIComponent(query)}&limit=10`);setDatasets(data.datasets??[]);setDiscovery(data);if(data.reason_if_unavailable)setError(data.reason_if_unavailable)})}}><label className="cert-select">Search datasets<input value={query} onChange={e=>setQuery(e.target.value)} disabled={!!busy||active}/></label><button className="tonal" disabled={!!busy||active||!provider?.runnable}>Discover datasets</button></form>{discovery&&<LiveFacts data={discovery} fields={['discovery_source','remote_query_attempted','remote_query_succeeded','remote_error_category','fetched_at']}/>} {datasets.length>0&&<label className="cert-select">Discovered dataset<select aria-label="Discovered dataset" value={datasetId} disabled={!!busy||active} onChange={e=>{const d=datasets.find(d=>d.dataset_id===e.target.value);setDatasetId(e.target.value);setRevision(d?.revision??'');setTarget(d?.target_candidates?.length===1?d.target_candidates[0]:'');resetIdentity()}}><option value="">Select a dataset</option>{datasets.map(d=><option key={d.dataset_id} value={d.dataset_id}>{d.name} · {d.dataset_id}</option>)}</select></label>}<div className="cert-selector"><label className="cert-select">Dataset identifier<input value={datasetId} disabled={!!busy||active} onChange={e=>{setDatasetId(e.target.value);resetIdentity()}}/></label><label className="cert-select">Revision<input value={revision} disabled={!!busy||active} onChange={e=>{setRevision(e.target.value);resetIdentity()}}/></label><label className="cert-select">Target<input value={target} disabled={!!busy||active} onChange={e=>{setTarget(e.target.value);resetIdentity()}}/></label></div><button className="tonal" disabled={!!busy||active||!provider?.runnable||!datasetId.trim()} onClick={()=>void act('Resolving contract',async()=>{const data=await liveRequest('/data/resolve',{method:'POST',body:request()});setContract(data.contract);setReport(null)})}>Resolve dataset</button></details>{context&&<p className="quiet">Workbench context: {label(context)}. Ingestion here does not change the workbench execution dataset.</p>}</Section>
    <Section title="Dataset contract">{contract?<><h3>{contract.dataset_name}</h3><LiveFacts data={contract} fields={['provider','dataset_id','revision','rows_available','columns','target','streaming_supported','cache_policy']}/><LiveFacts data={contract} fields={['dataset_fingerprint','sample_fingerprint','fingerprint_scope']}/><DataValue value={{license:contract.license,citation:contract.citation}}/><details><summary>Schema and feature roles</summary><DataValue value={{feature_names:contract.feature_names,feature_roles:contract.feature_roles,schema:contract.schema}}/></details></>:<Empty title="Resolve a dataset to inspect its contract"/>}</Section>
    <Section title="Dataset pre-certification" note="Checks are evaluated by the backend on a bounded sample. NOT_EVALUATED remains distinct from a passing check."><div className="cert-selector"><label className="cert-select">Sample rows<input aria-label="Sample rows" type="number" min="10" max="500" value={sampleRows} disabled={!!busy||active} onChange={e=>setSampleRows(Number(e.target.value))}/></label><button className="tonal" disabled={!!busy||active||!contract||!Number.isInteger(sampleRows)||sampleRows<10||sampleRows>500} onClick={()=>void act('Pre-certifying sample',async()=>setReport(await liveRequest('/data/precertify',{method:'POST',body:{...request(),sample_rows:sampleRows}})))}>Run pre-certification</button></div>{report?<><span className="cert-status">{report.overall_status}</span><LiveFacts data={report} fields={['schema_validity','target_validity','feature_roles','temporal_ordering','split_validity']}/><DataValue value={Object.fromEntries(Object.entries(report).filter(([k])=>!['schema_validity','target_validity','feature_roles','temporal_ordering','split_validity'].includes(k)))}/></>:<Empty title="No pre-certification report evaluated"/>}</Section>
    <Section title="Live data session" note="Bounded ingestion only. No model training. Session state remains in this workspace while switching surfaces."><div className="cert-selector"><label className="cert-select">Maximum rows<input type="number" min="10" max="2000" value={maxRows} disabled={!!busy||active} onChange={e=>setMaxRows(Number(e.target.value))}/></label><label className="cert-select">Batch size<input type="number" min="10" max={maxRows} value={batchSize} disabled={!!busy||active} onChange={e=>setBatchSize(Number(e.target.value))}/></label></div><div className="inline-actions"><button className="tonal" disabled={!!busy||active||!contract||!provider?.streaming_supported||!validBounds} onClick={()=>void act('Starting ingestion',async()=>{const data=await liveRequest('/data/sessions',{method:'POST',body:{...request(),max_rows:maxRows,batch_size:batchSize,cache_policy:'memory',auto_start:true}});setSession(data);setTelemetry(data.telemetry??null)})}>Start Data Session</button><button className="tonal" disabled={!!busy||!session||telemetry?.state==='STOPPED'} onClick={()=>void act('Stopping ingestion',async()=>{const stopped=await liveRequest(`/data/sessions/${encodeURIComponent(session!.session_id)}/stop`,{method:'POST'});setTelemetry(t=>({...t,...stopped}));const latest=await liveRequest(`/data/sessions/${encodeURIComponent(session!.session_id)}`);setSession(latest);setTelemetry(latest.telemetry)})}>Stop Data Session</button>{session&&<button className="text-action" disabled={!!busy} onClick={()=>void act('Refreshing session',async()=>{const s=await liveRequest(`/data/sessions/${encodeURIComponent(session.session_id)}`);setSession(s);setTelemetry(s.telemetry)})}>Refresh session</button>}</div>{session&&<p className="quiet">{session.session_id} · {session.dataset_id}</p>}</Section>
    <Section title="Runtime telemetry" note="Measured values from the active session endpoint. No simulated progress.">{pollError&&<p role="alert">{pollError}</p>}{telemetry?<><span className="cert-status">{telemetry.state}</span><LiveFacts data={telemetry} fields={['provider','dataset_id','revision','rows_available','rows_consumed','bytes_read','batch_count','batch_size','partition_count','active_partition','partition_progress','worker_count','rows_per_second','cache_state','cache_hits','cache_misses','train_rows','validation_rows','test_rows','device','current_operation','updated_at','errors']}/></>:<Empty title="No ingestion measurements yet"/>}</Section>
    <Section title="Runtime topology" note="Live descriptor; worker count and distributed state are supplied independently.">{runtime?<><LiveFacts data={runtime} fields={Object.keys(runtime)}/><ol className="cert-flow"><li><strong>{runtime.execution_backend}</strong><span>Workers: {runtime.worker_count??'Unavailable'}</span><span>Distributed: {String(runtime.distributed??'Unavailable')}</span></li></ol></>:<Empty title="Runtime descriptor unavailable"/>}</Section>
  </>
}
export function LiveFacts({data,fields}:{data:RecordData;fields:string[]}) {return <dl className="cert-facts cert-telemetry">{fields.filter(k=>Object.hasOwn(data,k)).map(k=><div key={k}><dt>{label(k)}</dt><dd className={data[k]==='NOT_EVALUATED'||data[k]==='NOT_AVAILABLE'?'live-not-evaluated':undefined}><DataValue value={data[k]}/></dd></div>)}</dl>}
