import type { ArtifactRecord, EvidenceRecord, Finding, RunSnapshot, RuntimeEvent } from '../contracts/types'
// This module is reachable only through the DEV-gated, dynamically imported gallery.
// Field-name mapping only; scientific values are neither rounded nor recomputed.
const fixtures = import.meta.glob('../../../CLAUDE_DESIGN_PACK/03_PREVIEW_FIXTURES/**/*.json', { eager:true, import:'default' }) as Record<string,any>
export function fixture(path:string):any {return fixtures[`../../../CLAUDE_DESIGN_PACK/03_PREVIEW_FIXTURES/${path}`]}
export function fixtureRun(folder:string):RunSnapshot {const r=fixture(`${folder}/run.json`);return {...r,goal:r.goal ?? '',startedAt:r.startedAt ?? '',updatedAt:r.updatedAt ?? '',elapsedMs:r.elapsedMs ?? 0,plan:r.plan ?? []}}
export function fixtureArtifacts(folder:string):ArtifactRecord[] {const r=fixtureRun(folder);return Object.entries(fixture(`${folder}/artifacts.json`) ?? {}).map(([id,a]:[string,any])=>({artifactId:a.artifactId ?? a.id ?? id,runId:a.runId ?? r.runId,label:a.label ?? a.title ?? a.name,kind:a.kind ?? (a.mimeType?.startsWith('image/')?'plot':'json'),artifactType:a.artifactType ?? a.artifact_type,mimeType:a.mimeType ?? 'application/json',createdAt:a.createdAt ?? '',content:a.content,description:a.description,evidenceIds:a.evidenceIds ?? a.evidence_ids ?? [],dataFingerprint:a.dataFingerprint ?? a.data_fingerprint,producerNodeId:a.producerNodeId ?? a.producing_step_id}))}
export function fixtureEvidence(folder:string):EvidenceRecord[] {return (fixture(`${folder}/evidence.json`) ?? []).map((e:any)=>({...e,evidenceId:e.evidenceId ?? e.evidence_id,runId:e.runId ?? e.run_id,testId:e.testId ?? e.test_id,title:e.title ?? e.test_name ?? e.test_id,status:e.status,metrics:Array.isArray(e.metrics)?e.metrics:Object.entries(e.metrics ?? {}).map(([name,value])=>({name,value})),provenance:e.provenance ?? [],createdAt:e.createdAt ?? e.timestamp ?? '',summary:e.summary ?? e.interpretation,parentNodeId:e.parentNodeId,rawSource:e}))}
export function fixtureFindings(folder:string):Finding[] {return (fixture(`${folder}/findings.json`) ?? []).map((f:any)=>({findingId:f.findingId ?? f.id,runId:fixtureRun(folder).runId,title:f.title ?? f.rule,summary:f.summary ?? f.message,evidenceIds:f.evidenceIds ?? [],severity:f.severity,sourceStatus:f.status,limitations:f.limitations ?? [],availableActions:f.availableActions ?? []}))}
export function fixtureEvents(folder:string):RuntimeEvent[] {return (fixture(`${folder}/events.json`) ?? []).map((e:any,i:number)=>({eventId:e.eventId ?? e.event_id,runId:e.runId ?? e.run_id,sequence:e.sequence ?? i,timestamp:typeof e.timestamp==='number'?new Date(e.timestamp*1000).toISOString():e.timestamp,type:e.type ?? e.event_type,nodeId:e.nodeId ?? e.node_id,title:e.title ?? e.action ?? e.event_type,message:e.message,status:e.status,evidenceIds:e.evidenceIds ?? e.evidence_refs,metadata:e.metadata}))}
