import { useEffect, useState } from 'react'
import type { AgentPlanPreview, RunSnapshot, ScenarioItem, WorkflowId } from '../contracts/types'
import { WorkbenchHeader } from '../components/WorkbenchHeader'
import { Composer } from '../features/composer/Composer'
import { EdaCanvas } from '../features/eda/EdaCanvas'
import { ResizableWorkspace } from '../components/ResizableWorkspace'
import { InvestigationWorkbench } from '../features/investigation/InvestigationWorkbench'
import { ExecutionReview } from '../features/investigation/ExecutionReview'
import { RunLedger } from '../features/history/RunHistoryModal'
import { ScientificComparison } from '../features/compare/RunCompareView'
import { TypedArtifactRenderer } from '../features/artifacts/TypedArtifactRenderer'
import { isAnalyticalObject } from '../features/investigation/presentation'
import { ReviewDialog } from '../components/ReviewDialog'
import { DataValue } from '../features/investigation/Science'
import { fixture,fixtureArtifacts,fixtureEvidence,fixtureEvents,fixtureFindings,fixtureRun } from './fixtures'
import './preview.css'

export const previewStates = [
 ['fresh','Fresh Review','predictive','Overview'],['configured','Configured Review','predictive','Overview'],['eda','EDA','predictive','Overview'],['plan','Plan Built','predictive','Overview'],['execution','Active Execution','predictive','Overview'],
 ['predictive','Completed Predictive','predictive','Overview'],['data','Predictive Data','predictive','Data'],['config','Predictive Configuration','predictive','Model'],['performance','Predictive Performance','predictive','Performance'],['explainability','Predictive Explainability','predictive','Explainability'],['validation','Predictive Validation','predictive','Validation'],['findings','Findings','predictive','Findings'],['evidence','Evidence','predictive','Evidence'],['governance','Governance','predictive','Governance'],['provenance','Provenance','predictive','Provenance'],['artifacts','Artifacts','predictive','Artifacts'],['history','History','predictive','Overview'],['replay','Replay','predictive','Overview'],['compare','Compare','predictive','Overview'],
 ['dl','Deep Learning','deep_learning','Overview'],['architecture','Deep Learning Architecture','deep_learning','Architecture'],['training','Deep Learning Training','deep_learning','Training'],['mf','Recommender MF','recommender/mf','Overview'],['ncf','Recommender NCF','recommender/ncf','Overview'],['fm','Recommender FM','recommender/fm','Overview'],['protocol','Evaluation Protocol','recommender/ncf','Evaluation Protocol'],['ranking','Ranking / Rating','recommender/mf','Ranking / Rating'],['coldstart','Coverage & Cold Start','recommender/ncf','Coverage & Cold Start'],['hrp','HRP','portfolio/hrp','Construction'],['minvar','Minimum Variance','portfolio/min_variance','Construction'],['erc','ERC','portfolio/erc','Risk'],['narrow','Narrow Pane','predictive','Performance'],['1024','1024px','predictive','Overview']
]
export default function UxPreview() {
  const initial=new URLSearchParams(location.search).get('state') ?? 'fresh'
  const [id,setId]=useState(previewStates.some(s=>s[0]===initial)?initial:'fresh')
  const state=previewStates.find(s=>s[0]===id)!, folder=state[2]
  const [section,setSection]=useState(state[3]),[selected,setSelected]=useState<string|null>(null),[artifact,setArtifact]=useState<string|null>(null)
  const [workflow,setWorkflow]=useState<WorkflowId|null>(null),[context,setContext]=useState<string|null>(null),[goal,setGoal]=useState(''),[plan,setPlan]=useState<AgentPlanPreview|null>(null),[scenario,setScenario]=useState<ScenarioItem|null>(null)
  const [notice,setNotice]=useState<string|null>(null)
  const [previewRatio,setPreviewRatio]=useState(65)
  const choose=(next:string)=>{setId(next);history.replaceState(null,'',`/dev/ux-preview?state=${next}`)}
  useEffect(()=>{setSection(state[3]);setSelected(null);setArtifact(null);setPlan(id==='plan'?fixture('fresh_review/sample_plan_preview.json'):null);setWorkflow(id==='fresh'?null:fixture('fresh_review/sample_plan_preview.json').workflowId);setContext(id==='fresh'?null:fixture('fresh_review/sample_plan_preview.json').contextId);setGoal(id==='fresh'?'':fixture('fresh_review/sample_plan_preview.json').goal)},[id])
  const run=fixtureRun(folder), artifacts=fixtureArtifacts(folder),evidence=fixtureEvidence(folder),events=fixtureEvents(folder)
  const define=['fresh','configured','eda','plan'].includes(id)
  const canvas=artifacts.find(isAnalyticalObject)
  // A bounded prefix of genuine runtime events, with stage statuses projected from that prefix.
  const observed=events.slice(0,25)
  const activeRun:RunSnapshot={...run,phase:'running',statusLabel:observed.at(-1)?.title ?? '',progress:{label:observed.at(-1)?.title ?? '',detail:observed.at(-1)?.message},plan:run.plan.map(s=>{const last=observed.filter(e=>e.nodeId===s.id).at(-1);return {...s,status:!last?'future':last.status.toLowerCase()==='completed'?'completed':last.status.toLowerCase()==='running'?'running':'attention'}})}
  const openHistory=()=>choose('history'), openCompare=()=>choose('compare')
  return <div className="preview-root"><div className="preview-bar"><strong>DEVELOPMENT PREVIEW</strong><select aria-label="Preview state" value={id} onChange={e=>choose(e.target.value)}>{previewStates.map(s=><option key={s[0]} value={s[0]}>{s[1]}</option>)}</select><span>{folder==='predictive'?'Production run fixture':'Canonical acceptance fixture'} · offline · no writes</span><a href="/">Live app ↗</a></div><div className={`preview-frame ${id==='1024'?'width-1024':''}`}><div className="start-workstation"><WorkbenchHeader mode={define?'DEFINE':id==='execution'?'EXECUTE':'INVESTIGATE'} onNew={()=>choose('fresh')} onHistory={openHistory} onCompare={openCompare} onSearch={()=>setNotice('Search uses the connected backend in the live app. This offline gallery is limited to the supplied fixture pack.')} onRuntime={()=>setNotice('Browser AI · Unavailable in offline fixture preview.')} isReplay={id==='replay'}/>
    {define ? <ResizableWorkspace key={id} isRightPaneUnlocked={id==='eda'} leftContent={<Composer capabilities={fixture('fresh_review/capabilities.json')} contexts={fixture('fresh_review/execution_contexts.json')} scenarios={fixture('fresh_review/scenarios.json')} selectedScenario={scenario} onSelectScenario={s=>{setScenario(s);setContext(s.compatible_context_id)}} workflow={workflow} setWorkflow={v=>{setWorkflow(v);setPlan(null)}} context={context} setContext={v=>{setContext(v);setPlan(null)}} goal={goal} setGoal={setGoal} plan={plan} onPlan={()=>{if(workflow===fixture('fresh_review/sample_plan_preview.json').workflowId && context===fixture('fresh_review/sample_plan_preview.json').contextId){setGoal(fixture('fresh_review/sample_plan_preview.json').goal);setPlan(fixture('fresh_review/sample_plan_preview.json'))}else setNotice('The supplied plan fixture covers the predictive credit context. Select Plan Built to inspect that exact plan.')}} onStart={()=>choose('execution')} busy={false} adapterMode="fixture" onOpenTestCatalog={()=>setNotice('catalog')}/>} rightContent={<EdaCanvas profile={fixture('fresh_review/sample_eda_credit.json')} activeScenario={scenario} loading={false} error={null} onOpenTestCatalog={()=>setNotice('catalog')}/>}/>
    : id==='history' ? <div className="standalone-preview"><div className="eyebrow">REVIEW LEDGER</div><h1>Run history</h1><RunLedger runs={fixture('history/sample_run_history.json').runs} onOpenRun={runId=>{if(runId===run.runId)choose('replay');else setNotice(`The ledger contains ${runId}; its replay payload is not included. The gallery Replay state shows ${run.runId}.`)}} onCompareRun={openCompare}/></div>
    : id==='compare' ? <div className="standalone-preview"><div className="eyebrow">SCIENTIFIC DIFF</div><h1>Compare reviews</h1><ScientificComparison result={fixture('compare/sample_compare_result.json')}/></div>
    : id==='execution' ? <ResizableWorkspace key={id} isRightPaneUnlocked={false} leftContent={<ExecutionReview run={activeRun} events={observed} evidence={evidence.filter(e=>observed.some(event=>event.evidenceIds?.includes(e.evidenceId)))} checkpoints={[]} onEvidence={id=>{choose('evidence');setSelected(id)}}/>}/>
    : id==='narrow' ? <ResizableWorkspace key={id} isRightPaneUnlocked={!!canvas} splitRatio={previewRatio} onSplitRatioChange={setPreviewRatio} leftContent={<div className="standalone-preview"><div className="eyebrow">RESPONSIVE INSPECTION</div><h1>Scientific figure in a narrow pane</h1><p>Use the divider to inspect continuous resizing. Double-click to reset.</p><DataValue value={fixture(`${folder}/analytical_result.json`).metrics}/></div>} rightContent={canvas&&<div className="analytical-inspector"><h2>{canvas.label}</h2><TypedArtifactRenderer artifact={canvas}/></div>}/>
    : <InvestigationWorkbench key={folder} run={run} canonical={fixture(`${folder}/analytical_result.json`)} artifacts={artifacts} evidence={evidence} findings={fixtureFindings(folder)} governance={fixture(`${folder}/governance.json`)} attestation={fixture(`${folder}/attestation.json`)} events={events} isReplay={id==='replay'} section={section} onSection={setSection} selectedEvidenceId={selected} onEvidence={eid=>{setSelected(eid);setSection('Evidence')}} selectedArtifactId={artifact} onArtifact={setArtifact} onAsk={()=>setNotice('Browser AI is unavailable in this offline preview.')} onDecision={()=>setNotice('Decision recording is disabled in the offline preview. Use the connected application to record a decision.')} onPin={()=>setNotice('Pinning is available in the live app. Offline fixtures remain unchanged.')}/>}
    <footer className="workstation-footer"><span>StART / Scientific review workspace</span><span>Fixture values · no synthetic science</span></footer></div></div>{notice&&<ReviewDialog title={notice==='catalog'?'Test catalog':'Offline preview'} onClose={()=>setNotice(null)}>{notice==='catalog'?<DataValue value={fixture('fresh_review/test_catalog.json')}/>:<p>{notice}</p>}</ReviewDialog>}</div>
}
