import type { StARTCapabilityManifest, WorkflowId } from '../../contracts/types'
import schemas from './modelSchemas.json'
import { capabilityLabel as name } from './runtimeSupport'
import { DataValue } from '../investigation/Science'
export type Parameters = Record<string, any>
export const algorithmContexts:Record<string,string>={matrix_factorization:'recommender_ratings_v1',neural_collaborative_filtering:'recommender_implicit_v1',factorization_machine:'recommender_contextual_v1',field_aware_factorization_machine:'recommender_ffm_v1'}
export const strategyValue:Record<string,string>={optuna_bayesian:'optuna',grid_search:'grid',random_search:'bounded_random_search'}
export function EngineeringControls({manifest,workflow,parameters:p,onChange,setContext}:{manifest:StARTCapabilityManifest;workflow:WorkflowId|null;parameters:Parameters;onChange:(p:Parameters)=>void;setContext:(s:string)=>void}) {
 const pred=manifest.domains.predictive_ml??{}, rec=manifest.domains.recommender_systems??{}, quant=manifest.domains.quantitative_finance??{}
 const tuning=workflow==='hyperparameter_tuning', neural=workflow==='deep_learning', predictive=['predictive_ml','fraud_anomaly_aml','data_diagnostics','model_diagnostics','calibration','robustness','explainability','hyperparameter_tuning','deep_learning'].includes(workflow??'')
 const set=(k:string,v:any)=>onChange({...p,...(k==='model'?{hyperparameters:{}}:{}),[k]:v})
 const select=(label:string,key:string,values:string[],mapping:Record<string,string>={},disabled=false)=><label className="stacked-label">{label}<select disabled={disabled} value={p[key]??''} onChange={e=>set(key,e.target.value)}><option value="">Backend default</option>{values.map(v=><option key={v} value={mapping[v]??v}>{name(v)}</option>)}</select></label>
 const nested=(label:string,group:string,key:string,values:string[],labels:Record<string,string>={})=><label className="stacked-label">{label}<select value={p[group]?.[key]??''} onChange={e=>set(group,{...p[group],[key]:e.target.value})}><option value="">Backend default</option>{values.map(v=><option key={v} value={v}>{labels[v]??name(v)}</option>)}</select></label>
 const modelOptions=(pred.primary_classification_models??[]).filter((v:string)=>!neural||v==='mlp')
 const modelSchema=(schemas as Record<string,any>)[p.model]??{}
 return <div className="engineering-controls">
 {predictive&&<><details open><summary>Model</summary>{select(neural?'Neural estimator':'Model', 'model',modelOptions)}<p className="quiet">Optional dependencies are verified by the backend at execution; unavailable estimators fail closed. No model is substituted.</p></details>
 {!tuning&&<><details><summary>Preprocessing</summary><div className="configuration-fields">{nested('Missing values','preprocessing','imputation',['median','mean','most_frequent'])}{nested('Scaling','preprocessing','scaler',['none','standard','minmax','robust'])}{nested('Outlier mitigation','preprocessing','outlier_mitigation',['none','iqr','zscore','winsorize'],{none:'None',iqr:'IQR Clipping (1.5x)',zscore:'Z-Score (3.0 sigma)',winsorize:'Winsorize (1%-99%)'})}{nested('Categorical encoding','preprocessing','encoding',['ordinal','onehot','target','frequency','none'],{ordinal:'Ordinal Encoding',onehot:'One-Hot Encoding',target:'Target Encoding (Smoothed)',frequency:'Frequency Encoding',none:'None'})}</div><p className="quiet">Deterministic preprocessing pipeline fitted strictly on training data with zero test-set leakage.</p></details>
 <details><summary>Split / evaluation design</summary>{nested('Split strategy','split','strategy',['stratified','random','time_series'],{stratified:'Stratified Holdout',random:'Random Holdout',time_series:'Time Series Split'})}<label className="stacked-label">Test fraction<input type="number" min="0.05" max="0.5" step="0.05" value={p.split?.test_size??''} placeholder="Backend default: 0.25" onChange={e=>set('split',{...p.split,test_size:e.target.value===''?undefined:Number(e.target.value)})}/></label><p className="quiet">Holdout evaluation with zero data leakage across train and test partitions.</p></details>
 <details><summary>Hyperparameters</summary>{!p.model?<p>Select a model to configure its parameters.</p>:<div className="configuration-fields">{Object.entries(modelSchema).map(([key,raw])=>{const schema=raw as any;return <label className="stacked-label" key={key}>{name(key)}{schema.type==='cat'?<select value={p.hyperparameters?.[key]===undefined?'':JSON.stringify(p.hyperparameters[key])} onChange={e=>set('hyperparameters',{...p.hyperparameters,[key]:e.target.value===''?undefined:JSON.parse(e.target.value)})}><option value="">Backend default</option>{(schema.choices??schema.grid).map((v:any)=><option key={JSON.stringify(v)} value={JSON.stringify(v)}>{String(v)}</option>)}</select>:<input type="number" min={schema.low} max={schema.high} step={schema.type==='int'?1:'any'} placeholder="Backend default" value={p.hyperparameters?.[key]??''} onChange={e=>set('hyperparameters',{...p.hyperparameters,[key]:e.target.value===''?undefined:Number(e.target.value)})}/>}</label>})}</div>}<p className="quiet">Parameter descriptors come from the backend model registry. Unset values use backend defaults.</p></details></>}
 {tuning?<details open><summary>Tuning</summary>{select('Search strategy','strategy',(pred.tuning_strategies??[]).filter((s:string)=>s!=='none'),strategyValue)}{select('Primary metric','primary_metric',['auc_roc','pr_auc','recall','f1'])}<p className="quiet">The backend owns search spaces and internal validation. Inspect the resulting trial parameters after execution.</p></details>:<details><summary>Tuning</summary><p>Use the Hyperparameter Tuning workflow for a bounded experiment. This pipeline runs the selected fixed parameters.</p></details>}
 <details><summary>Explainability</summary><p className="quiet">Post-fit explainability metrics are evaluated deterministically by the diagnostics pipeline.</p><DataValue value={pred.explainability}/></details>
 {!tuning&&<details><summary>Sensitivity Lab</summary><p>Top Features = {pred.sensitivity_analysis?.max_features}</p><div className="shock-grid" aria-label="Sensitivity shock grid">{(pred.sensitivity_analysis?.shocks_grid??[]).map((v:number)=><span key={v}>{v>0?'+':''}{v*100}%{v===0?' · baseline':''}</span>)}</div><label className="stacked-label">Sensitivity mode<select value={p.sensitivity?.mode??''} onChange={e=>onChange({...p,sensitivity_mode:e.target.value,sensitivity:{mode:e.target.value}})}><option value="">Backend default</option>{(pred.sensitivity_analysis?.modes??[]).filter((s:string)=>['one_at_a_time','parallel_basket'].includes(s)).map((s:string)=><option key={s} value={s}>{name(s)}</option>)}</select></label><p className="quiet">ROC-AUC · fixed-model feature shocks. Results are calculated by the backend.</p></details>}
 </>}
 {workflow==='recommender_system'&&<details open><summary>Recommender model</summary><label className="stacked-label">Algorithm<select value={p.algorithm??''} onChange={e=>{onChange({algorithm:e.target.value});setContext(algorithmContexts[e.target.value])}}><option value="" disabled>Select algorithm</option>{(rec.algorithms??[]).filter((s:string)=>algorithmContexts[s]).map((s:string)=><option key={s} value={s}>{name(s)}</option>)}</select></label><p className="quiet">The matching canonical context is selected with the algorithm. FM and FFM remain distinct.</p></details>}
 {workflow==='fraud_anomaly_aml'&&<details><summary>Fraud task availability</summary><DataValue value={{runnable:manifest.domains.fraud_anomaly?.executable_techniques,deferred:manifest.domains.fraud_anomaly?.deferred_techniques}}/></details>}
 {workflow==='quantitative_finance'&&<details open><summary>Portfolio & scenario configuration</summary><div className="configuration-fields"><label className="stacked-label">Portfolio Optimizer<select value={p.optimizer??p.portfolio_optimizer??''} onChange={e=>onChange({...p,optimizer:e.target.value,portfolio_optimizer:e.target.value})}><option value="">Backend default (HRP)</option><option value="hrp">Hierarchical Risk Parity (HRP)</option><option value="min_var">Minimum Variance</option><option value="erc">Equal Risk Contribution (ERC)</option></select></label><label className="stacked-label">Scenario Stress Type<select value={p.scenario??p.scenario_type??''} onChange={e=>onChange({...p,scenario:e.target.value,scenario_type:e.target.value})}><option value="">Backend default (Asset Tail Stress)</option><option value="asset_tail_stress">Historical Asset Tail Stress</option><option value="factor_macro">Factor / Macro Shock</option><option value="reverse_stress">Reverse Stress (Mahalanobis)</option><option value="correlation_breakdown">Correlation Breakdown</option></select></label><label className="stacked-label">Shock Magnitude<input type="number" step="0.05" min="-0.50" max="0.50" value={p.shock_magnitude??''} placeholder="Default: -0.20 (-20%)" onChange={e=>onChange({...p,shock_magnitude:e.target.value===''?undefined:Number(e.target.value)})}/></label></div><p className="quiet">Portfolio optimization and scenario stress parameters are dispatched to the quantitative risk engine.</p></details>}
 </div>
}
