import { LiveRunPresentation, type PresentationKind } from '../certification/LiveRunPresentation'
import { useEffect, useState } from 'react'
import { ArrowUpRight, Pin, X } from 'lucide-react'
import type { ArtifactRecord, AttestationState, EvidenceRecord, Finding, GovernanceState, RunLineage, RunSnapshot, RuntimeEvent } from '../../contracts/types'
import { ResizableWorkspace } from '../../components/ResizableWorkspace'
import { TypedArtifactRenderer } from '../artifacts/TypedArtifactRenderer'
import { ConfigurationCodeView } from '../canvas/ConfigurationCodeView'
import { analysisSections, ArtifactFigure, ModelAnalysis } from './ModelAnalysis'
import { Bars, CopyValue, DataBlock, DataValue, Empty, LineFigure, ScoreStrip, Section } from './Science'
import { fromArtifacts, isAnalyticalObject, label, object, type ScientificRecord } from './presentation'
import { ExecutionTrace } from './ExecutionReview'
import { formatDateTime } from '../../utils/formatTimestamp'

export interface InvestigationProps {
  run: RunSnapshot; canonical?: ScientificRecord | null; artifacts: ArtifactRecord[]; evidence: EvidenceRecord[]; findings: Finding[];
  governance: GovernanceState | null; attestation: AttestationState | null; events: RuntimeEvent[]; isReplay?: boolean;
  section: string; onSection: (s: string) => void; selectedEvidenceId?: string | null; onEvidence: (id: string) => void;
  onAsk?: (id?: string) => void; onChallenge?: (id?: string) => void; onDecision?: () => void;
  onPin?: (a: ArtifactRecord | EvidenceRecord) => void; isPinned?: (id: string) => boolean;
  selectedArtifactId?: string | null; onArtifact?: (id: string | null) => void; lineage?: RunLineage | null; onLoadRun?: (id: string) => void;
}
export function FindingsQueue({ findings, onEvidence, onChallenge, compact = false }: { findings: Finding[]; onEvidence: (id: string) => void; onChallenge?: (id?: string) => void; compact?: boolean }) {
  const sourceStatus = (f: Finding) => (f as Finding & {sourceStatus?:string}).sourceStatus
  const priority = (f: Finding) => ({critical:0,attention:1,FAIL:0,WARN:1,info:2,PASS:2}[f.severity ?? sourceStatus(f) ?? 'info'] ?? 3)
  const ordered = [...findings].sort((a,b) => priority(a)-priority(b))
  return ordered.length ? <div className="findings-queue">{(compact ? ordered.slice(0,3) : ordered).map(f => <article className="editorial-finding" key={f.findingId} data-severity={f.severity ?? sourceStatus(f)}><div className="eyebrow">{f.severity ?? sourceStatus(f) ?? 'Severity not supplied'} · {f.evidenceIds.length ? `${f.evidenceIds.length} supporting records` : 'Evidence linkage not supplied'}</div><h3>{f.title}</h3><p>{f.summary}</p>{f.limitations?.map((l,i) => <p className="limitation" key={i}>{l}</p>)}<div className="inline-actions">{f.evidenceIds.map((id,i) => <button className="text-action" onClick={() => onEvidence(id)} key={id}>{i === 0 ? 'Inspect evidence' : `Record ${i+1}`}<ArrowUpRight size={13}/></button>)}{onChallenge && f.availableActions.includes('challenge') && <button className="text-action" onClick={() => onChallenge(f.evidenceIds[0])}>Challenge</button>}</div></article>)}</div> : <Empty title="No findings supplied"/>
}
export function EvidenceDetail({ evidence, artifacts, onAsk, onChallenge, onPin, pinned }: { evidence: EvidenceRecord; artifacts: ArtifactRecord[]; onAsk?: () => void; onChallenge?: () => void; onPin?: () => void; pinned?: boolean }) {
  return <div className="evidence-detail"><div className="eyebrow">{evidence.status} · {evidence.testId}</div><h2>{evidence.title}</h2>{evidence.summary && <p>{evidence.summary}</p>}<div className="inline-actions">{onAsk && <button className="text-action" onClick={onAsk}>Ask Why</button>}{onChallenge && <button className="text-action" onClick={onChallenge}>Challenge</button>}{onPin && <button className="icon-button" aria-label={pinned ? 'Unpin evidence' : 'Pin evidence'} title={pinned ? 'Unpin evidence' : 'Pin evidence'} onClick={onPin}><Pin size={15} fill={pinned ? 'currentColor' : 'none'}/></button>}</div><DataBlock title="Metrics & criteria" data={evidence.metrics}/><DataBlock title="Criteria & limitations" data={(evidence as EvidenceRecord & {rawSource?:ScientificRecord}).rawSource ? {criteria:(evidence as any).rawSource.thresholds,limitations:(evidence as any).rawSource.limitations,reproducibility:(evidence as any).rawSource.repro} : undefined}/><DataBlock title="Provenance" data={evidence.provenance}/><DataBlock title="Linked artifacts" data={artifacts.filter(a => a.evidenceIds?.includes(evidence.evidenceId)).map(a => ({title:a.label,artifact_id:a.artifactId}))}/><Section title="Record identity"><CopyValue value={evidence.evidenceId}/><p className="quiet">{evidence.parentNodeId} · {formatDateTime(evidence.createdAt)}</p></Section><details><summary>View raw record</summary><pre className="raw-source">{JSON.stringify((evidence as any).rawSource ?? evidence,null,2)}</pre></details></div>
}
export function InvestigationWorkbench(p: InvestigationProps) {
  const a = p.canonical ?? fromArtifacts(p.artifacts)
  const family = a.model_family ?? (p.run.contextId?.startsWith('recommender') ? 'recommender' : p.run.workflowId)
  const sections = analysisSections(family)
  const [query,setQuery] = useState('')
  const [inspector,setInspector] = useState<ArtifactRecord | null>(null)
  const [rawArtifact,setRawArtifact] = useState<ArtifactRecord | null>(null)
  useEffect(() => { setInspector(null) }, [p.run.runId])
  const nav = (s: string) => { setInspector(null); setRawArtifact(null); p.onArtifact?.(null); p.onSection(s) }
  const selectArtifact = (artifact: ArtifactRecord) => {if(isAnalyticalObject(artifact)){setInspector(artifact);setRawArtifact(null)}else{setRawArtifact(artifact);setInspector(null)}p.onArtifact?.(artifact.artifactId)}
  useEffect(() => { const artifact=p.artifacts.find(a => a.artifactId===p.selectedArtifactId); if(artifact) selectArtifact(artifact) }, [p.selectedArtifactId,p.run.runId])
  const selected = p.evidence.find(e => e.evidenceId === p.selectedEvidenceId)
  const d = object(a.diagnostics)
  const allSections = [...sections,'Findings','Evidence','Artifacts','Provenance','Governance']
  const current = allSections.includes(p.section) ? p.section : 'Overview'
  return <div className="investigation-system" data-testid="investigation-workbench">
    <nav className="investigation-nav" aria-label="Investigation sections"><div className="nav-desktop"><span className="nav-group">ANALYSIS</span>{sections.map(s => <button key={s} aria-current={current===s ? 'page' : undefined} onClick={() => nav(s)}>{s}</button>)}<span className="nav-group">REVIEW</span>{['Findings','Evidence','Artifacts','Provenance','Governance'].map(s => <button key={s} aria-current={current===s ? 'page' : undefined} onClick={() => nav(s)}>{s}<span>{s==='Findings' ? p.findings.length : s==='Evidence' ? p.evidence.length : ''}</span></button>)}</div><select aria-label="Investigation section" className="nav-compact" value={current} onChange={e => nav(e.target.value)}><optgroup label="Analysis">{sections.map(s => <option key={s}>{s}</option>)}</optgroup><optgroup label="Review">{['Findings','Evidence','Artifacts','Provenance','Governance'].map(s => <option key={s}>{s}</option>)}</optgroup></select></nav>
    <ResizableWorkspace isRightPaneUnlocked={!!inspector} ariaLabelLeft="Analysis" ariaLabelRight="Analytical object inspector" leftContent={<div className="investigation-content">
      <div className="section-heading-row"><div><div className="eyebrow">{label(family ?? 'Review')} / {p.isReplay ? 'REPLAY' : 'INVESTIGATE'}</div><h1>{current === 'Overview' ? label(a.technique ?? p.run.workflowId) : current}</h1></div>{current === 'Overview' && <div className="disposition-summary"><span>Backend disposition</span><strong>{p.governance?.disposition ?? 'Not supplied'}</strong></div>}</div>
      {p.isReplay && <p className="replay-notice">REPLAY · Read-only reconstruction · {formatDateTime(p.run.updatedAt)}</p>}
      {current === 'Overview' && <>
        {p.run.workflowId==='hyperparameter_tuning'&&<p className="attention-note">This overview reflects the supplied canonical analysis. Inspect Tuning for the requested estimator, trial results and best parameters; the backend may supply a separate canonical model.</p>}
        <p className="review-context">{label(a.data_selection?.dataset_name ?? p.run.contextId)}<span> / </span>{label(a.task_type ?? p.run.workflowId)}</p>
        <Section title="Model result" note="Canonical analytical result"><ScoreStrip data={Object.fromEntries(Object.entries(object(a.metrics)).slice(0,6))}/></Section>
        <div className="overview-editorial"><div><Section title="Findings & diagnostic insights" note="Reviewer attention, ordered by severity"><FindingsQueue findings={p.findings} onEvidence={p.onEvidence} onChallenge={p.isReplay ? undefined : p.onChallenge} compact/>{p.findings.length > 3 && <button className="text-action" onClick={() => nav('Findings')}>All {p.findings.length} findings <ArrowUpRight size={14}/></button>}</Section>
        {a.deterministic_findings?.some((f: ScientificRecord) => !p.findings.some(existing => existing.findingId === f.id)) && <Section title="Canonical model checks" note="Model analysis scope · separate from the execution evidence ledger">{a.deterministic_findings.filter((f: ScientificRecord) => !p.findings.some(existing => existing.findingId === f.id)).map((f: ScientificRecord,i: number) => <article className="model-check" key={f.id ?? i}><span className={`scientific-status status-${String(f.status).toLowerCase()}`}>{f.status}</span><div><h3>{f.rule}</h3><p>{f.message}</p></div></article>)}</Section>}</div>
        <div className="overview-figure"><Section title={['portfolio','quantitative_finance'].includes(family) ? 'Allocation' : family === 'deep_learning' ? 'Training convergence' : family === 'recommender' ? 'Ranking at K' : 'Discrimination'}>
          {['portfolio','quantitative_finance'].includes(family) ? <Bars data={object(d.weights)}/> : family === 'deep_learning' ? <LineFigure xLabel="Epoch" yLabel="Loss" series={[{name:'Training',x:d.training_curve?.epochs ?? [],y:d.training_curve?.train_loss ?? []},{name:'Validation',x:d.training_curve?.epochs ?? [],y:d.training_curve?.val_loss ?? []}]}/> : family === 'recommender' ? <Bars name="NDCG at K" data={object(d.ranking?.ndcg_at_k)}/> : <LineFigure unitSquare reference xLabel="False positive rate" yLabel="True positive rate" series={[{name:'ROC',x:d.roc_curve?.fpr ?? [],y:d.roc_curve?.tpr ?? []}]}/>}
          <button className="text-action" onClick={() => nav(['portfolio','quantitative_finance'].includes(family) ? 'Allocation' : family === 'deep_learning' ? 'Training' : family === 'recommender' ? 'Ranking / Rating' : 'Performance')}>Open analysis <ArrowUpRight size={14}/></button>
        </Section><dl className="review-inventory"><div><dt>Evidence records</dt><dd>{p.evidence.length}</dd></div><div><dt>Reproducible artifacts</dt><dd>{p.artifacts.length}</dd></div><div><dt>Completed</dt><dd>{formatDateTime(p.run.updatedAt)}</dd></div></dl></div></div>
        <details className="review-objective"><summary>Engineering objective</summary><p>{p.run.goal || 'Not supplied'}</p></details><ExecutionTrace events={p.events}/>
      </>}
      {sections.includes(current) && current !== 'Overview' && <ModelAnalysis section={current} a={{...a,model_family:family}} artifacts={p.artifacts} events={p.events}/>}
      {({Tuning:'tuning',Explainability:'xai',Sensitivity:'sensitivity',Allocation:'portfolio',Scenario:'scenario'} as Record<string,PresentationKind>)[current]&&<LiveRunPresentation runId={p.run.runId} kind={({Tuning:'tuning',Explainability:'xai',Sensitivity:'sensitivity',Allocation:'portfolio',Scenario:'scenario'} as Record<string,PresentationKind>)[current]}/>}
      {current === 'Findings' && <FindingsQueue findings={p.findings} onEvidence={p.onEvidence} onChallenge={p.isReplay ? undefined : p.onChallenge}/>}
      {current === 'Evidence' && <><input className="ledger-search" type="search" aria-label="Filter evidence" placeholder="Search tests, titles, or record IDs" value={query} onChange={e => setQuery(e.target.value)}/>{selected ? <><button className="text-action back-link" onClick={() => p.onEvidence('')}>← Evidence ledger</button><EvidenceDetail evidence={selected} artifacts={p.artifacts} onAsk={p.onAsk ? () => p.onAsk!(selected.evidenceId) : undefined} onChallenge={!p.isReplay && p.onChallenge ? () => p.onChallenge!(selected.evidenceId) : undefined} onPin={p.onPin ? () => p.onPin!(selected) : undefined} pinned={p.isPinned?.(selected.evidenceId)}/></> : <div className="evidence-ledger">{p.evidence.filter(e => `${e.title} ${e.testId} ${e.evidenceId}`.toLowerCase().includes(query.toLowerCase())).map(e => <button className="evidence-row" key={e.evidenceId} onClick={() => p.onEvidence(e.evidenceId)}><span><strong>{e.title}</strong><small>{e.testId} · {e.parentNodeId || 'Stage not supplied'}</small></span><span className="evidence-key-metric">{e.metrics[0] && `${label(e.metrics[0].name)} · ${typeof e.metrics[0].value === 'object' && e.metrics[0].value !== null ? 'Structured values' : e.metrics[0].value}`}</span><span className={`scientific-status status-${e.status.toLowerCase()}`}>{e.status}</span></button>)}</div>}</>}
      {current === 'Artifacts' && <><p className="lead">Reproducible outputs backing this review. Select an object to inspect its supplied content.</p>{rawArtifact && <Section title={rawArtifact.label}><button className="text-action" onClick={() => {setRawArtifact(null);p.onArtifact?.(null)}}>Close record</button><ArtifactFigure artifact={rawArtifact}/></Section>}<div className="artifact-ledger">{p.artifacts.map(art => <article key={art.artifactId}><div><span className="eyebrow">{art.artifactType ?? art.kind}</span><h3>{art.label}</h3><p>{art.description}</p><CopyValue value={art.artifactId} truncate/></div><div className="inline-actions"><button className="text-action" onClick={() => selectArtifact(art)}>Inspect <ArrowUpRight size={14}/></button>{p.onPin && <button className="icon-button" aria-label="Pin artifact" title="Pin artifact" onClick={() => p.onPin!(art)}><Pin size={15}/></button>}</div></article>)}</div></>}
      {current === 'Provenance' && <><Section title="Run lineage"><div className="run-lineage">{p.run.parentRunId && <><button className="text-action" onClick={() => p.onLoadRun?.(p.run.parentRunId!)}>{p.run.parentRunId}</button><span>→</span></>}<CopyValue value={p.run.runId}/>{p.lineage?.children?.map(c => <button className="text-action" key={c.runId} onClick={() => p.onLoadRun?.(c.runId)}>→ {c.runId} · {c.intervention ?? c.status}</button>)}</div>{p.lineage?.parameterDelta && <DataValue value={p.lineage.parameterDelta}/>}</Section><DataBlock title="Scientific provenance" data={a.provenance}/><Section title="Attestation">{p.attestation ? <><CopyValue value={p.attestation.merkleRoot} truncate/><DataValue value={{evidence_count:p.attestation.evidenceCount,artifact_count:p.attestation.artifactCount,reproducibility_id:p.attestation.reproducibilityId,created:formatDateTime(p.attestation.createdAt)}}/></> : <Empty title="Attestation not supplied"/>}</Section><ExecutionTrace events={p.events}/></>}
      {current === 'Governance' && <><div className="governance-decision"><div className="eyebrow">CANONICAL BACKEND DISPOSITION</div><h2>{p.governance?.disposition ?? 'Not supplied'}</h2><p>{p.governance?.rationale ?? 'No policy rationale supplied.'}</p><DataValue value={{policy_decision:p.governance?.policyDecision,evidence_coverage:p.governance?.evidenceCoverage}}/></div><DataBlock title="Unresolved review items" data={p.governance?.unresolvedItems}/><div className="inline-actions"><button className="text-action" onClick={() => nav('Evidence')}>Inspect evidence</button><button className="text-action" onClick={() => nav('Provenance')}>Inspect provenance</button>{!p.isReplay && p.onDecision && <button className="primary" onClick={p.onDecision}>Record Approval</button>}</div>{p.isReplay && <p className="quiet">Historical decisions are read-only.</p>}</>}
    </div>} rightContent={inspector && <div className="analytical-inspector"><div className="inspector-header"><h2>{inspector.label}</h2><button className="icon-button" onClick={() => {setInspector(null);p.onArtifact?.(null)}} aria-label="Close analytical inspector" title="Close inspector"><X size={16}/></button></div>{inspector.artifactType === 'resolved_configuration' ? <ConfigurationCodeView rawConfig={inspector.content}/> : <TypedArtifactRenderer artifact={inspector}/>}<DataBlock title="Provenance" data={{artifact_id:inspector.artifactId,fingerprint:inspector.dataFingerprint,producing_stage:inspector.producerNodeId}}/>{inspector.evidenceIds?.map(id => <button className="text-action" key={id} onClick={() => {setInspector(null);p.onEvidence(id)}}>Inspect evidence · {id}</button>)}</div>}/>
  </div>
}
