"""Institutional Portfolio Intelligence Package (Gate 2 & Gate 3).

Core components:
- contracts: Typed dataclasses, schemas, threshold provenance, and constraint verification structures.
- constraints: Independent deterministic post-solve constraint verification engine.
- hrp: Hierarchical Risk Parity, tree builders, linkage sensitivity, and bootstrap stability.
- herc: Hierarchical Equal Risk Contribution (Raffinot, 2018).
- risk_contributions: Euler risk contribution decomposition (asset & cluster level).
- optimization: Equal-Weight, Equal Risk Contribution (ERC), and Efficient Frontier.
- black_litterman: Black-Litterman model, implied equilibrium returns, view processing, and posterior allocation.
- robust_mvo: Convex robust mean-variance optimization under ellipsoidal uncertainty and sensitivity grid.
- cvar: Rockafellar-Uryasev CVaR / Expected-Shortfall Linear Programming optimization.
- max_diversification: Maximum Diversification Portfolio (MDP).
- tracking_error: Tracking-error constrained benchmark-relative optimization.
- rebalance: Turnover calculation, transaction cost estimation, and RebalanceDecision generation.
- comparison: Multi-method portfolio comparison engine.
- walk_forward: Non-leaky out-of-sample walk-forward evaluation harness.
- artifacts: Typed ArtifactRecord generators with cryptographic semantic payloads.
- evidence_bridge: Conversion from typed analytical outputs to TestResult and EvidenceRecord.
"""

from __future__ import annotations

from start.portfolio.artifacts import (
    ArtifactRecord,
    ArtifactSpec,
    render_active_risk_decomposition_artifact,
    render_asset_weights_artifact,
    # Gate 5 Artifacts
    render_backtest_summary_artifact,
    render_bl_allocation_artifact,
    render_bl_returns_artifact,
    render_brinson_attribution_artifact,
    render_carino_linking_artifact,
    render_cluster_allocation_artifact,
    render_cluster_risk_artifact,
    render_cluster_tree_artifact,
    render_covariance_comparison_artifact,
    # Gate 4 Artifacts
    render_covariance_diagnostics_artifact,
    render_cvar_tail_risk_artifact,
    render_dendrogram_artifact,
    render_distance_matrix_artifact,
    render_duration_diagnostics_artifact,
    render_efficient_frontier_artifact,
    render_exception_transition_artifact,
    render_factor_return_attribution_artifact,
    render_factor_risk_model_artifact,
    render_factor_risk_waterfall_artifact,
    render_herc_hierarchy_artifact,
    render_multi_method_comparison_artifact,
    render_psd_repair_artifact,
    render_raw_correlation_artifact,
    render_raw_covariance_heatmap_artifact,
    render_rebalance_waterfall_artifact,
    render_reverse_stress_profile_artifact,
    render_risk_contribution_artifact,
    render_robust_mvo_sensitivity_artifact,
    render_scenario_active_comparison_artifact,
    render_scenario_asset_contribution_artifact,
    render_scenario_factor_contribution_artifact,
    render_scenario_group_heatmap_artifact,
    render_scenario_pnl_waterfall_artifact,
    render_scenario_sensitivity_curve_artifact,
    render_scenario_set_ranking_artifact,
    render_seriated_correlation_artifact,
    render_tail_comparison_artifact,
    render_tail_loss_distribution_artifact,
    render_tail_risk_contribution_artifact,
    render_tail_severity_artifact,
    render_tracking_error_artifact,
    render_var_pnl_timeline_artifact,
)
from start.portfolio.attribution import (
    compute_brinson_attribution,
    compute_carino_multi_period_linking,
    compute_factor_return_attribution,
)
from start.portfolio.black_litterman import (
    BLACK_LITTERMAN_APPLICABILITY,
    compute_black_litterman_posterior,
    compute_implied_equilibrium_returns,
    solve_black_litterman,
)
from start.portfolio.comparison import compare_portfolio_methods
from start.portfolio.constraints import (
    CONSTRAINT_TOLERANCE_DEFAULT,
    verify_portfolio_constraints,
)
from start.portfolio.contracts import (
    ActiveRiskDecompositionResult,
    ActiveScenarioResult,
    BlackLittermanResult,
    BootstrapStabilityResult,
    BrinsonAttributionResult,
    CarinoLinkedAttributionResult,
    ChallengeResolution,
    ChallengeState,
    ConstraintType,
    ConstraintVerificationResult,
    ConstraintViolation,
    CopheneticResult,
    CovarianceComparisonResult,
    CovarianceDiagnostics,
    CovarianceEstimate,
    CVaROptimizationResult,
    DeterminismTier,
    DurationDiagnosticsResult,
    EfficientFrontierResult,
    EqualRiskContributionResult,
    FactorConstraintSpec,
    FactorDataIntegrityResult,
    FactorReturnAttributionResult,
    FactorRiskDecompositionResult,
    FactorRiskModelResult,
    FrontierPoint,
    GroupConstraintSpec,
    GroupCoveragePolicy,
    HERCResult,
    HierarchicalTreeResult,
    LinkageSensitivityResult,
    MaxDiversificationResult,
    MethodApplicability,
    MethodComparisonResult,
    MetricHorizon,
    PartitionContract,
    PortfolioWeights,
    PSDRepairMethod,
    PSDRepairResult,
    RebalanceDecision,
    RepricingMethod,
    ReturnConvention,
    ReverseStressNorm,
    ReverseStressResult,
    ReverseStressSpec,
    RiskContributionResult,
    RobustMVOResult,
    RobustSensitivityPoint,
    RobustSensitivityResult,
    ScenarioDataIntegrityResult,
    ScenarioResult,
    ScenarioSensitivityPoint,
    ScenarioSensitivityResult,
    ScenarioSetResult,
    ScenarioShock,
    ScenarioSpec,
    ScenarioType,
    SensitivitySpec,
    ShockSpace,
    ShockUnit,
    TailBacktestResult,
    TailModelComparisonResult,
    TailRiskContributionResult,
    TailRiskEstimate,
    TailRiskMethod,
    TailSeverityResult,
    TailSignConvention,
    ThresholdSource,
    ThresholdValue,
    TrackingErrorResult,
    TransactionCostSpec,
    UncertaintyDerivationPolicy,
    ViewUncertaintyPolicy,
    WalkForwardResult,
    validate_horizon_alignment,
)
from start.portfolio.covariance import (
    compare_covariance_estimators,
    diagnose_covariance,
    repair_psd_covariance,
)
from start.portfolio.cvar import (
    CVAR_APPLICABILITY,
    solve_cvar_portfolio,
)
from start.portfolio.evidence_bridge import (
    active_risk_decomp_to_evidence,
    active_scenario_to_evidence,
    black_litterman_to_evidence,
    bootstrap_stability_to_evidence,
    brinson_to_evidence,
    carino_to_evidence,
    challenge_result_to_diagnostic_evidence,
    constraint_verification_to_evidence,
    cophenetic_to_evidence,
    covariance_comparison_to_evidence,
    covariance_diagnostics_to_evidence,
    cvar_to_evidence,
    duration_diagnostics_to_evidence,
    efficient_frontier_to_evidence,
    equal_weight_to_evidence,
    erc_to_evidence,
    factor_data_integrity_to_evidence,
    factor_return_attribution_to_evidence,
    factor_risk_decomp_to_evidence,
    factor_risk_model_to_evidence,
    group_scenario_to_evidence,
    herc_to_evidence,
    linkage_sensitivity_to_evidence,
    max_diversification_to_evidence,
    method_comparison_to_evidence,
    psd_repair_to_evidence,
    rebalance_decision_to_evidence,
    reverse_stress_to_evidence,
    risk_contributions_to_evidence,
    robust_mvo_to_evidence,
    robust_sensitivity_to_evidence,
    scenario_data_integrity_to_evidence,
    scenario_result_to_evidence,
    scenario_sensitivity_to_evidence,
    scenario_set_to_evidence,
    tail_backtest_to_evidence,
    tail_comparison_to_evidence,
    tail_contribution_to_evidence,
    tail_risk_estimate_to_evidence,
    tail_severity_to_evidence,
    tracking_error_to_evidence,
    tree_to_evidence,
    walk_forward_to_evidence,
)
from start.portfolio.factor_risk import (
    build_linear_factor_model,
    decompose_active_risk,
    decompose_factor_risk,
    validate_factor_alignment,
    validate_factor_data_integrity,
)
from start.portfolio.herc import (
    HERC_APPLICABILITY,
    solve_herc,
)
from start.portfolio.hrp import (
    bootstrap_cluster_stability,
    cophenetic_distance_diagnostic,
    correlation_distance,
    hrp_weights_and_tree,
    linkage_sensitivity_analysis,
    quasi_diagonalize,
    validate_linkage_geometry,
)
from start.portfolio.max_diversification import (
    MAX_DIV_APPLICABILITY,
    solve_max_diversification,
)
from start.portfolio.optimization import (
    solve_equal_risk_contribution,
    solve_equal_weight,
    trace_efficient_frontier,
)
from start.portfolio.rebalance import (
    build_rebalance_decision,
    compute_transaction_costs,
    compute_turnover,
)
from start.portfolio.risk_contributions import calculate_risk_contributions
from start.portfolio.robust_mvo import (
    ROBUST_MVO_APPLICABILITY,
    robust_mvo_sensitivity_grid,
    solve_robust_mvo,
)
from start.portfolio.scenario import (
    apply_active_scenario,
    apply_asset_return_scenario,
    apply_benchmark_active_scenario,
    apply_delta_gamma_scenario,
    apply_factor_scenario,
    apply_group_scenario_decomposition,
    compare_scenario_set,
    create_scenario_shock,
    evaluate_scenario,
    evaluate_scenario_sensitivity_grid,
    normalize_shock,
    replay_historical_scenario,
    solve_reverse_stress,
    validate_repricing_shock_compatibility,
    validate_scenario_data_integrity,
)
from start.portfolio.tail_risk import (
    compare_tail_risk_models,
    compute_exception_duration_diagnostics,
    compute_historical_var_es,
    compute_parametric_normal_var_es,
    compute_tail_risk_contributions,
    compute_tail_severity,
    run_comprehensive_tail_backtest,
)
from start.portfolio.tracking_error import (
    TRACKING_ERROR_APPLICABILITY,
    solve_tracking_error_constrained,
)
from start.portfolio.walk_forward import run_walk_forward_evaluation

__all__ = [
    # Contracts & Types
    "ThresholdSource",
    "ThresholdValue",
    "DeterminismTier",
    "MethodApplicability",
    "ConstraintType",
    "ConstraintViolation",
    "ConstraintVerificationResult",
    "TransactionCostSpec",
    "FactorConstraintSpec",
    "GroupConstraintSpec",
    "GroupCoveragePolicy",
    "MetricHorizon",
    "ReturnConvention",
    "validate_horizon_alignment",
    "ChallengeState",
    "ChallengeResolution",
    "ViewUncertaintyPolicy",
    "UncertaintyDerivationPolicy",
    "PortfolioWeights",
    "RiskContributionResult",
    "HierarchicalTreeResult",
    "LinkageSensitivityResult",
    "BootstrapStabilityResult",
    "CopheneticResult",
    "EqualRiskContributionResult",
    "FrontierPoint",
    "EfficientFrontierResult",
    "MethodComparisonResult",
    "WalkForwardResult",
    "BlackLittermanResult",
    "RobustMVOResult",
    "RobustSensitivityPoint",
    "RobustSensitivityResult",
    "CVaROptimizationResult",
    "HERCResult",
    "MaxDiversificationResult",
    "TrackingErrorResult",
    "RebalanceDecision",
    # Gate 4 Contracts
    "PSDRepairMethod",
    "CovarianceDiagnostics",
    "PSDRepairResult",
    "CovarianceEstimate",
    "CovarianceComparisonResult",
    "FactorRiskModelResult",
    "FactorRiskDecompositionResult",
    "ActiveRiskDecompositionResult",
    "FactorReturnAttributionResult",
    "BrinsonAttributionResult",
    "CarinoLinkedAttributionResult",
    "FactorDataIntegrityResult",
    # Solvers & Engines
    "calculate_risk_contributions",
    "correlation_distance",
    "validate_linkage_geometry",
    "quasi_diagonalize",
    "hrp_weights_and_tree",
    "cophenetic_distance_diagnostic",
    "linkage_sensitivity_analysis",
    "bootstrap_cluster_stability",
    "solve_equal_weight",
    "solve_equal_risk_contribution",
    "trace_efficient_frontier",
    "compare_portfolio_methods",
    "run_walk_forward_evaluation",
    "CONSTRAINT_TOLERANCE_DEFAULT",
    "verify_portfolio_constraints",
    "compute_implied_equilibrium_returns",
    "compute_black_litterman_posterior",
    "solve_black_litterman",
    "solve_robust_mvo",
    "robust_mvo_sensitivity_grid",
    "solve_cvar_portfolio",
    "solve_herc",
    "solve_max_diversification",
    "solve_tracking_error_constrained",
    "compute_turnover",
    "compute_transaction_costs",
    "build_rebalance_decision",
    # Gate 4 Engines
    "diagnose_covariance",
    "repair_psd_covariance",
    "compare_covariance_estimators",
    "validate_factor_alignment",
    "build_linear_factor_model",
    "decompose_factor_risk",
    "decompose_active_risk",
    "validate_factor_data_integrity",
    "compute_factor_return_attribution",
    "compute_brinson_attribution",
    "compute_carino_multi_period_linking",
    # Applicability
    "BLACK_LITTERMAN_APPLICABILITY",
    "ROBUST_MVO_APPLICABILITY",
    "CVAR_APPLICABILITY",
    "HERC_APPLICABILITY",
    "MAX_DIV_APPLICABILITY",
    "TRACKING_ERROR_APPLICABILITY",
    # Artifacts
    "ArtifactSpec",
    "ArtifactRecord",
    "render_dendrogram_artifact",
    "render_raw_correlation_artifact",
    "render_seriated_correlation_artifact",
    "render_distance_matrix_artifact",
    "render_cluster_tree_artifact",
    "render_cluster_allocation_artifact",
    "render_asset_weights_artifact",
    "render_risk_contribution_artifact",
    "render_cluster_risk_artifact",
    "render_efficient_frontier_artifact",
    "render_bl_returns_artifact",
    "render_bl_allocation_artifact",
    "render_robust_mvo_sensitivity_artifact",
    "render_cvar_tail_risk_artifact",
    "render_herc_hierarchy_artifact",
    "render_tracking_error_artifact",
    "render_rebalance_waterfall_artifact",
    "render_multi_method_comparison_artifact",
    # Gate 4 Artifacts
    "render_covariance_diagnostics_artifact",
    "render_raw_covariance_heatmap_artifact",
    "render_psd_repair_artifact",
    "render_covariance_comparison_artifact",
    "render_factor_risk_model_artifact",
    "render_factor_risk_waterfall_artifact",
    "render_active_risk_decomposition_artifact",
    "render_factor_return_attribution_artifact",
    "render_brinson_attribution_artifact",
    "render_carino_linking_artifact",
    # Gate 5 Artifacts
    "render_tail_loss_distribution_artifact",
    "render_var_pnl_timeline_artifact",
    "render_exception_transition_artifact",
    "render_duration_diagnostics_artifact",
    "render_tail_severity_artifact",
    "render_backtest_summary_artifact",
    "render_tail_comparison_artifact",
    "render_tail_risk_contribution_artifact",
    # Evidence Bridges
    "tree_to_evidence",
    "linkage_sensitivity_to_evidence",
    "cophenetic_to_evidence",
    "bootstrap_stability_to_evidence",
    "risk_contributions_to_evidence",
    "equal_weight_to_evidence",
    "erc_to_evidence",
    "efficient_frontier_to_evidence",
    "method_comparison_to_evidence",
    "walk_forward_to_evidence",
    "black_litterman_to_evidence",
    "challenge_result_to_diagnostic_evidence",
    "robust_mvo_to_evidence",
    "robust_sensitivity_to_evidence",
    "cvar_to_evidence",
    "herc_to_evidence",
    "max_diversification_to_evidence",
    "tracking_error_to_evidence",
    "rebalance_decision_to_evidence",
    "constraint_verification_to_evidence",
    # Gate 4 Evidence Bridges
    "covariance_diagnostics_to_evidence",
    "psd_repair_to_evidence",
    "covariance_comparison_to_evidence",
    "factor_risk_model_to_evidence",
    "factor_risk_decomp_to_evidence",
    "active_risk_decomp_to_evidence",
    "factor_return_attribution_to_evidence",
    "brinson_to_evidence",
    "carino_to_evidence",
    "factor_data_integrity_to_evidence",
    # Gate 5 Evidence Bridges & Engines
    "tail_risk_estimate_to_evidence",
    "tail_backtest_to_evidence",
    "duration_diagnostics_to_evidence",
    "tail_severity_to_evidence",
    "tail_contribution_to_evidence",
    "tail_comparison_to_evidence",
    "compute_historical_var_es",
    "compute_parametric_normal_var_es",
    "compute_tail_risk_contributions",
    "compute_tail_severity",
    "compute_exception_duration_diagnostics",
    "run_comprehensive_tail_backtest",
    "compare_tail_risk_models",
    "TailSignConvention",
    "TailRiskMethod",
    "TailRiskEstimate",
    "TailBacktestResult",
    "DurationDiagnosticsResult",
    "TailSeverityResult",
    "TailRiskContributionResult",
    "TailModelComparisonResult",
    # Gate 6 Artifacts, Bridges, Engines & Contracts
    "render_scenario_pnl_waterfall_artifact",
    "render_scenario_asset_contribution_artifact",
    "render_scenario_factor_contribution_artifact",
    "render_scenario_active_comparison_artifact",
    "render_scenario_group_heatmap_artifact",
    "render_scenario_set_ranking_artifact",
    "render_scenario_sensitivity_curve_artifact",
    "render_reverse_stress_profile_artifact",
    "scenario_result_to_evidence",
    "active_scenario_to_evidence",
    "group_scenario_to_evidence",
    "scenario_set_to_evidence",
    "scenario_sensitivity_to_evidence",
    "reverse_stress_to_evidence",
    "scenario_data_integrity_to_evidence",
    "apply_active_scenario",
    "apply_asset_return_scenario",
    "apply_factor_scenario",
    "apply_delta_gamma_scenario",
    "apply_benchmark_active_scenario",
    "apply_group_scenario_decomposition",
    "compare_scenario_set",
    "evaluate_scenario",
    "evaluate_scenario_sensitivity_grid",
    "solve_reverse_stress",
    "replay_historical_scenario",
    "normalize_shock",
    "create_scenario_shock",
    "validate_repricing_shock_compatibility",
    "validate_scenario_data_integrity",
    "ScenarioType",
    "ShockSpace",
    "ShockUnit",
    "RepricingMethod",
    "ReverseStressNorm",
    "PartitionContract",
    "ScenarioShock",
    "SensitivitySpec",
    "ScenarioSpec",
    "ScenarioResult",
    "ActiveScenarioResult",
    "ScenarioSetResult",
    "ScenarioSensitivityPoint",
    "ScenarioSensitivityResult",
    "ReverseStressSpec",
    "ReverseStressResult",
    "ScenarioDataIntegrityResult",
]
