import { useEffect, useRef, useState } from 'react'
import type { PinnedItem } from '../../contracts/types'
import type { StartBackend } from '../../contracts/backend'
import { ReviewDialog } from '../../components/ReviewDialog'
import { label } from '../investigation/presentation'
export function CommandPalette(p: {isOpen:boolean;onClose:()=>void;onOpenRun:(id:string)=>void|Promise<void>;onSelectEvidence?:(id:string,run?:string)=>void;onSelectArtifact?:(id:string,run?:string)=>void;onSelectTest?:(id:string)=>void;onSelectContext?:(id:string)=>void;pinnedItems:PinnedItem[];backend:StartBackend}) {
  const [query,setQuery]=useState(''), [results,setResults]=useState<{id:string;category:string;title:string;subtitle?:string;data?:any}[]>([]), [index,setIndex]=useState(0), [error,setError]=useState(''), [loading,setLoading]=useState(false)
  const input = useRef<HTMLInputElement>(null), list = useRef<HTMLDivElement>(null)
  useEffect(()=>{if(p.isOpen){setQuery('');setIndex(0);requestAnimationFrame(()=>input.current?.focus())}},[p.isOpen])
  useEffect(()=>{if(!p.isOpen)return;let alive=true;setError('');setLoading(true);const timer=setTimeout(async()=>{try{const r=query.trim() ? await p.backend.searchGlobal?.(query.trim()) ?? [] : p.pinnedItems.map(v=>({id:v.itemId,category:v.itemType,title:v.label,subtitle:v.runId,data:{runId:v.runId}}));if(alive){setResults([...r].sort((a,b)=>a.category.localeCompare(b.category)));setIndex(0)}}catch(e){if(alive)setError((e as Error).message)}finally{if(alive)setLoading(false)}},150);return()=>{alive=false;clearTimeout(timer)}},[query,p.isOpen,p.backend,p.pinnedItems])
  useEffect(()=>{list.current?.querySelector('[aria-selected="true"]')?.scrollIntoView({block:'nearest'})},[index])
  const select=(r:typeof results[number])=>{const run=r.data?.runId ?? r.data?.run_id;if(r.category==='run')p.onOpenRun(r.id);else if(r.category==='evidence')p.onSelectEvidence?.(r.id,run);else if(r.category==='artifact')p.onSelectArtifact?.(r.id,run);else if(r.category==='test')p.onSelectTest?.(r.id);else if(r.category==='context'||r.category==='scenario')p.onSelectContext?.(r.data?.compatible_context_id ?? r.id);p.onClose()}
  if(!p.isOpen)return null
  return <ReviewDialog title="Search workspace" onClose={p.onClose}><input ref={input} role="combobox" aria-label="Search runs, evidence, artifacts, tests, and contexts" aria-controls="workspace-results" aria-expanded="true" aria-activedescendant={results[index] ? `search-result-${index}` : undefined} value={query} placeholder="Search runs, evidence, artifacts, tests, contexts…" onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setIndex(i=>results.length ? (i+(e.key==='ArrowDown'?1:-1)+results.length)%results.length:0)}if(e.key==='Enter'&&results[index]){e.preventDefault();select(results[index])}}}/><div ref={list} className="search-results" id="workspace-results" role="listbox">{loading ? <p className="quiet">Searching…</p> : results.map((r,i)=><div key={`${r.category}-${r.id}-${i}`}>{(i===0 || results[i-1].category!==r.category)&&<div className="nav-group">{label(r.category)}</div>}<button id={`search-result-${i}`} role="option" aria-selected={index===i} className="search-result" onClick={()=>select(r)} onMouseEnter={()=>setIndex(i)}><strong>{r.title}</strong><small>{r.subtitle}</small></button></div>)}</div>{error&&<p role="alert">{error}</p>}{!loading&&!results.length&&<p className="quiet">{query?'No matching records.':'Type to search the workspace. Pinned records appear here.'}</p>}<p className="keyboard-help">↑ ↓ Navigate · Enter Open · Esc Close</p></ReviewDialog>
}
