import * as webllm from "@mlc-ai/web-llm";
import { QualitativeFinding, WebReviewerSubmission } from "../types/start_schema";

export const PINNED_MODEL_ID = "SmolLM2-1.7B-Instruct-q4f16_1-MLC";

export interface WebLLMInitState {
  isSupported: boolean;
  isLoaded: boolean;
  isLoading: boolean;
  progressText: string;
  progressPercent: number;
  error: string | null;
}

class WebLLMService {
  private engine: webllm.MLCEngineInterface | null = null;
  private selectedModel = PINNED_MODEL_ID;

  async checkWebGPUSupport(): Promise<boolean> {
    if (typeof navigator === "undefined" || !("gpu" in navigator)) {
      return false;
    }
    try {
      const adapter = await (navigator as any).gpu.requestAdapter();
      return !!adapter;
    } catch {
      return false;
    }
  }

  async initialize(
    onProgress?: (progress: { text: string; progress: number }) => void
  ): Promise<void> {
    const isSupported = await this.checkWebGPUSupport();
    if (!isSupported) {
      throw new Error("WebGPU is not supported on this browser or hardware device.");
    }

    if (this.engine) {
      return;
    }

    this.engine = await webllm.CreateMLCEngine(this.selectedModel, {
      initProgressCallback: (report) => {
        if (onProgress) {
          onProgress({ text: report.text, progress: report.progress * 100 });
        }
      },
    });
  }

  isReady(): boolean {
    return this.engine !== null;
  }

  async generateQualitativeReview(
    runId: string,
    sessionId: string,
    domain: string,
    evidenceRecords: Array<{ evidence_id: string; test_id: string; status: string; metrics: Record<string, any> }>,
    onStreamChunk?: (chunk: string) => void
  ): Promise<WebReviewerSubmission> {
    if (!this.engine) {
      throw new Error("WebLLM Engine is not initialized. Please enable Browser AI Reviewer first.");
    }

    // Build evidence universe summary for prompt
    const evidenceSummary = evidenceRecords
      .slice(0, 10)
      .map(
        (r) =>
          `- [${r.evidence_id}] ${r.test_id} (${r.status}): ${Object.keys(r.metrics).join(", ")}`
      )
      .join("\n");

    const systemPrompt = `You are an evidence-grounded engineering reviewer serving ML, deep learning, quantitative finance, and software development workflows.
You must adhere strictly to evidence discipline:
1. Reason ONLY from the permitted EvidenceRecords provided.
2. For each qualitative finding, cite the exact bracketed Evidence ID (e.g. [${evidenceRecords[0]?.evidence_id || "EV-01"}]) and metric name.
3. Structure your response strictly as valid JSON matching:
{
  "executive_summary": "string",
  "findings": [
    {
      "finding_id": "F-01",
      "severity": "LOW" | "MEDIUM" | "HIGH",
      "title": "string",
      "description": "string",
      "evidence_refs": [{"evidence_id": "string", "metric_name": "string"}],
      "recommendation": "string"
    }
  ],
  "limitations": ["string"],
  "suggested_actions": ["string"]
}`;

    const userPrompt = `Analytical Domain: ${domain}
Permitted Evidence Universe:
${evidenceSummary}

Please evaluate the empirical evidence records and provide your structured engineering review in JSON.`;

    const messages: webllm.ChatCompletionMessageParam[] = [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt },
    ];

    let fullText = "";
    const chunks = await this.engine.chat.completions.create({
      messages,
      stream: true,
      temperature: 0.1,
      max_tokens: 800,
    });

    for await (const chunk of chunks) {
      const delta = chunk.choices[0]?.delta?.content || "";
      fullText += delta;
      if (onStreamChunk) {
        onStreamChunk(delta);
      }
    }

    // Parse JSON strictly without fabricating findings on failure
    try {
      let cleaned = fullText.trim();
      if (cleaned.startsWith("```")) {
        const firstNl = cleaned.indexOf("\n");
        if (firstNl !== -1) cleaned = cleaned.substring(firstNl + 1);
        if (cleaned.endsWith("```")) cleaned = cleaned.substring(0, cleaned.length - 3);
        cleaned = cleaned.trim();
      }

      const parsed = JSON.parse(cleaned);
      if (!parsed || typeof parsed !== "object") {
        throw new Error("Decoded output is not a valid JSON object.");
      }

      return {
        run_id: runId,
        session_id: sessionId,
        model_name: this.selectedModel,
        executive_summary: parsed.executive_summary || "Engineering review synthesized.",
        findings: Array.isArray(parsed.findings) ? parsed.findings : [],
        limitations: Array.isArray(parsed.limitations) ? parsed.limitations : [],
        suggested_actions: Array.isArray(parsed.suggested_actions) ? parsed.suggested_actions : [],
      };
    } catch (parseErr: any) {
      throw new Error(
        `Structured review parse failure: ${parseErr.message || "Invalid JSON generated by local model"}`
      );
    }
  }
}

export const webLLMService = new WebLLMService();
